### ISSUE TITLE
Add binning information to the commondata format

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#1006]
People complain that the data theory plots in validphys are ugly because they don't include the binning.

In order to solve that we would need e able to read them from somewhere and in turn we need to write them somewhere. 

We could make use of the flexibly afforded by having the parser implementation in python to be able to add these things more easily although it is likely that buildmaster would need to be modified as well, but we could disregard the c++ reading part. I think the right format would be to have `min` and `max` in addition to `central` for each of the three kinematics. I think the more reasonable course of action would be to make it an optional feature so that we don't have to update all of the buildmaster files at once. Then the plots would adapt to whether we have binning information or not.

 While we are on it we could look into having more than three kinematics, which is limiting.

This could (and likely should) be done after we properly utilize the python based parser.

 Does that sound reasonable?

cc @enocera

**Comment by scarlehoff** [comment]
Fixed in #1813
