### ISSUE TITLE
Plot fktable x grid

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#1089]
The way I imagine it, one would have the existing PDF plots (e.g. the replica and the band ones), in exactly this basis to start with

https://github.com/NNPDF/nnpdf/blob/51be8fd30d94ef76e6a94e9670c17850d0a71cf8/validphys2/src/validphys/convolution.py#L57

with the `draw` method supplemented with the ability to plot ticks for the xgrid for a bunch of fktables.

Possible refinements include sizing the ticks based on some measure of contribution to the cross section (this would need some thought, e.g. is it scaled by the exp unc of different datapoints?) or the ability to change basis (which shouldn't be very hard but again would involve deciding how to deal with fractional ticks.).

**Comment by scarlehoff** [comment]
I guess this issue (and associated PRs) can be closed since this was a red-herring all along. We can come back to it if someone is interested.
