### ISSUE TITLE
Theory covmat prescription still determined by length of theoryids

### ISSUE THREAD

**Issue by RosalynLP** [NNPDF/nnpdf#1182]
I noticed that the theory covmat prescription in `covs_pt_prescrip` is determined still using the length of `theoryids` and whether or not "`fivetheories`" is set. Since the introduction of `point_prescription` to the runcard this seems like a non-ideal way to do things, especially since people will need to specify both

```
point_prescription: "5bar pt"
fivetheories: "bar"
```

to get it to work. A simple thing to do it move to pure reliance on` point_prescription` to tell the action what prescription to use, however this might deprecate some old runcards. I don't think this is so much of a problem as they weren't widely run by anyone other than me and @voisey, but it is something to be aware of.

If e.g.  @voisey @Zaharid think it's OK I'd like to go ahead and update this.

**Comment by scarlehoff** [comment]
This was (likely) fixed by #1524 or #1528
