### ISSUE TITLE
Comparing datasets with variants on the same name

### ISSUE THREAD

**Issue by RosalynLP** [NNPDF/nnpdf#1196]
In #1194 I am trying to do plots where you compare the chi2s/phis of datasets between different fits. But when the datasets have different name variants between fits this can be obfuscated. E.g. SLACP_dwsh versus SLACP_dw vs SLACP; they're all the "same dataset" but different implementations, and ideally they should be compared with one another because the only thing that's changing is the theory uncertainties in this case.

The same applies in the chi2 bar plots or tables. While I understand there is an important distinction between each dataset implementation, I feel that for plotting purposes it'd be useful to have some of them appear together.

This ties in with the general question of dataset labels on plots; while a name like ATLAS_TTB_DIFF_8TEV_LJ_TTRAPNORM might be informative for us it looks a bit horrendous in plots for papers or talks, so maybe we could add to the plotting files a "plotting_name", like r"ATLAS $t\bar{t}$ lepton + jet  $t\bar{t}$ rapidity" or something, and then that can be what appears in the plots. This could then solve the above issue by giving e.g. all the SLACP datasets a "SLAC $F_2^p$" name, and having all datasets with the same plotting_name together.

It might be best to have the option of whether to use these plotting_names or not as a flag.

What are people's thoughts on this? There might be  a better way of dealing with these two issues.

**Comment by scarlehoff** [comment]
This will actually be relevant again with the `variants`

**Comment by scarlehoff** [comment]
Given that the appetite for this doesn't seem to exist (although I agree it would be nice) I'll close it as not planned.
