### ISSUE TITLE
C++ loading of theory covmat can't deal with spaces in process names

### ISSUE THREAD

**Issue by RosalynLP** [NNPDF/nnpdf#1229]
Following on from #1225 I tried launching a few replicas with the updated runcard (as it appears in #1226) for 3pt scale variation and I get an error at the Cholesky decomposition stage. If the runcard in now correct this might be due to something to do with data keyword and the theory covmat module.

**Comment by scarlehoff** [comment]
C++ version of thcovmat is now deprecated.
