### ISSUE TITLE
2D lumi plots (absolute and pull)

### ISSUE THREAD

**Issue by juanrojochacon** [NNPDF/nnpdf#1282]
Now in the Section 9 of the paper we evaluate the pull between two luminosities as a function of mX, which is a rather useful estimator to quantify in a quick way the compatibility between two PDF fits. We would like to produce these plots also for the 2D differential lumis, with the same definition but with now as a function of both mX and yX. We already have the 2D lumi plots, we just need to combine them for two PDF sets.

@cschwan @voisey I think this is what we need right?

**Comment by scarlehoff** [comment]
These were added.
