### ISSUE TITLE
Add test to check exp and th covmat indexes match up

### ISSUE THREAD

**Issue by voisey** [NNPDF/nnpdf#1299]
Add a test to avoid a repeat of https://github.com/NNPDF/nnpdf/pull/1232

**Comment by scarlehoff** [comment]
@andreab1997 is this still relevant, or your changes sort of fixed this?

**Comment by andreab1997** [comment]
I believe we have now a regression test for the thcovmat so this should have been addressed. I believe that should be enough: if we screw up the order most likely the matrix will come out different
