### ISSUE TITLE
`ThPredictionsResult` should not use C++

### ISSUE THREAD

**Issue by siranipour** [NNPDF/nnpdf#1347]
At the moment when computing theory predictions we make calls to `C++`

https://github.com/NNPDF/nnpdf/blob/70ca11df5c42079ef4d3daec774a4222473372a7/validphys2/src/validphys/results.py#L131

afaict this can be replaced in favour of `validphys.convolution`. In particular the stats no longer need to be done using C++ too. However, before fixing this I just want to make sure of the following:

When we have

https://github.com/NNPDF/nnpdf/blob/70ca11df5c42079ef4d3daec774a4222473372a7/validphys2/src/validphys/results.py#L108

Is this equivalent to:

```python
np.std(self._rawdata, axis=1)
```

because at the moment, (for NMC for example)

```python
np.allclose(self.std_error, np.std(self._rawdata, axis=1)
# False
```
cc @scarrazza

**Comment by scarlehoff** [comment]
Hi @siranipour, are you working on this atm? Otherwise I'll try to do this together with #1420

**Comment by siranipour** [comment]
I tried saw it was a bit more involved than an afternoons work and gave up. I'm happy to take a look properly if you like?

**Comment by scarlehoff** [comment]
No. Don't worry. Between 1420 and the pineappl/eko business I'll have to deal with all of this anyway.

But no worries I'll need you to review the PR which I anticipate that will also be more than one afternoon :P

**Comment by scarlehoff** [comment]
There is a problem for this, currently `libNNPDF` allows to do the convolutions without cuts.
Instead, validphys does not https://github.com/NNPDF/nnpdf/blob/2fc5586489e33c0a1c63f8ac93f2db390fe998b7/validphys2/src/validphys/convolution.py#L116

As a result some runcard cannot work: https://github.com/NNPDF/nnpdf/blob/master/validphys2/examples/data_theory_comparison.yaml

I don't know why MW added that error, @Zaharid  @siranipour, any ideas? Does libNNPDF always apply errors internally (if so, that runcard would be wrong?)

Other than that, this issue should be easy to deal with <sub>(famous last words)</sub>

**Comment by Zaharid** [comment]
Equivalent in what regard? The requirement is to have cuts that are compatible with the data in the fktables of which the internal cuts are an example. So we either need that or find a way to deal with the missing points.

**Comment by scarlehoff** [comment]
You said 

> The problem is that some data points are not present in some fktables and are in practice always cut out.

and

> Libnnpdf would always return zero for convolutions of these

I wonder whether settings the cuts to `internal` will have the same practical effect (in this case that the points that would be set to 0 by libNNPDF are dropped). If that were to be the case then having cuts as a dependent of the convolutions is fine to me.

In any case, the runcard _is_ wrong in that cuts are being applied by virtue of some points not existing at all in the prediction.

**Comment by scarlehoff** [comment]
Indeed, my solution is basically what MW suggest in there. I'll do that. The current way of doing it is far from the best and if someone wants to recover some specific behaviour in that case they can implement it anew in python.

I'll add a warning explaining the problem for people trying to use old runcards.
