### ISSUE TITLE
`n3fit_data_utils` should use python constructs

### ISSUE THREAD

**Issue by siranipour** [NNPDF/nnpdf#1403]
There is a lot of `validphys.n3fit_data_utils` that uses C++.

E.g

https://github.com/NNPDF/nnpdf/blob/6744f998ab8b7cfc1aac43e9257be40d526ebea4/validphys2/src/validphys/n3fit_data_utils.py#L76

can go in favour of [fkparser](https://github.com/NNPDF/nnpdf/blob/master/validphys2/src/validphys/fkparser.py).

In particular we should remove this function's (and its internal calls) reliance on C++

https://github.com/NNPDF/nnpdf/blob/6744f998ab8b7cfc1aac43e9257be40d526ebea4/validphys2/src/validphys/n3fit_data_utils.py#L182

by not needing the line 

https://github.com/NNPDF/nnpdf/blob/6744f998ab8b7cfc1aac43e9257be40d526ebea4/validphys2/src/validphys/n3fit_data.py#L254

**Comment by scarlehoff** [comment]
This is now done. The next step regards the `n3fit` code itself which is tracked in #1683
