### ISSUE TITLE
Remove compatibility with 3.1

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#1405]
As per https://docs.nnpdf.science/releases.html#id4
having published the 4.0 paper we no longer need to support 3.1-era runcards and fits. To some approximation that means `rm -rf nnpdfcpp` but I think also things like the complicated backwards compatibility support for `experiments` (which has been very useful) would no longer be needed, leading to some opportunities for simplification. 

It would be probably good to tag the code with the last version supporting 3.1 compatibility.

**Comment by Zaharid** [comment]
@enocera @scarrazza Is there a reason why we would want to keep the nnpdfcpp directory any longer? Apart from moving the data around and so on.

**Comment by scarlehoff** [comment]
Beyond removing `nnpdfcpp` we should also remove all the extra files the fit creates which are not needed (as all information is in the `.json` file)

**Comment by Zaharid** [comment]
I am wondering if we should wait until the paper is actually published for this.

In the meantime here what has been collected so far

   - [ ] Tag code.
   - [ ] Delete nnpdfcpp (easy, but requires changing builds as well).
   - [ ] Amend documentation (easy, should be mostly removing stuff, but needs to be done together with each change)
   - [ ] Remove old fit format data (easy, but requires some work and an issue).
   - [ ] Remove compatibility with `experiments` (hard, as there is a bit of tricky code involved cc @siranipour ).
   - [ ]  Possibly simplify closure test commondata cc @RoyStegeman (probably hard).

**Comment by scarlehoff** [comment]
> I am wondering if we should wait until the paper is actually published for this.

You mean you would like to have the "publish tag" in which compatibility with 3.1 is kept?

**Comment by Zaharid** [comment]
I mean having the paper accepted in a journal.

**Comment by scarlehoff** [comment]
Yes. With a companion "published tag". Because otherwise it makes no difference for the code.

**Comment by Zaharid** [comment]
Yes indeed. If everything goes well that tag won't be very different from the current one.
