### ISSUE TITLE
Error commondata when running a closure test

### ISSUE THREAD

**Issue by RoyStegeman** [NNPDF/nnpdf#1409]
While trying to run a closure test I got an error related to the line in commondata parser below. It removes the DATA_ prefix from commondata filenames, but instead, while running the closure test a commondata filename starting with FILTER_ was passed, so the prefix was not fully removed and as a result the name of the dataset is not recognised. 

https://github.com/NNPDF/nnpdf/blob/f020b0bf2926fc85196441825896c8f955f1e69b/validphys2/src/validphys/commondataparser.py#L23 

I also noticed these lines below. Does this mean DATA_ is the old format, and if I get a name with FILTER_ in the data parser above, the FILTER_ prefix should simply be removed or is there a more important difference between the two? 

https://github.com/NNPDF/nnpdf/blob/f020b0bf2926fc85196441825896c8f955f1e69b/validphys2/src/validphys/loader.py#L238-L243

Maybe @siranipour knows more about this?

**Comment by siranipour** [comment]
Ah yes this is definitely broken and I'll take a look at fixing it with high priority! Could you kindly post the full traceback and runcard you used so I can work on it.

**Comment by Zaharid** [comment]
No idea why commondataparser is getting the nme in such a convoluted way. Surely one can just use `spec.name`?

**Comment by siranipour** [comment]
Yes that should work in fact, @RoyStegeman can you check if you replace that line with `setname = spec.name` fixes your issue?

**Comment by RoyStegeman** [comment]
Since problem was only with nor removing the full FILTER_ prefix, that does solve it (and it's what I did for now). I'm not sure, though, about the difference between FILTER_ and DATA_, so perhaps the fact that it now doesn't give an error for FILTER_ is undesirable in some other way?

**Comment by Zaharid** [comment]
I think FILTER files are made written with the cuts applied to them, much to my horror. Then somewhere there is a complicated machinery to rebuild them in a sensible way.

**Comment by Zaharid** [comment]
In particular see all the complexity in here https://github.com/NNPDF/nnpdf/blob/f020b0bf2926fc85196441825896c8f955f1e69b/validphys2/src/validphys/loader.py#L259 If we could get rid of it, so much the better.

**Comment by Zaharid** [comment]
And for yet more context https://github.com/NNPDF/nnpdf/pull/203

**Comment by RoyStegeman** [comment]
> And for yet more context #203

Thanks I'll have a look. Though my aim for now is just to produce some (correct) closure test results, not to delve deep into the machinery.
