### ISSUE TITLE
Add integrability dataset to theory 

### ISSUE THREAD

**Issue by RoyStegeman** [NNPDF/nnpdf#1410]
@enocera for the parametrization business I created some new FK tables for V, V3 and V8 with a single point at x=1e-9 (see the example below for the .dat file, they're all the same). Now I would like to include these in a theory, one with the same settings as the baseline theory 200, such that they are not only stored on my system. What is the best way to do this? 

```
INTEGXV	0	1
   1	DIS_XV	1.000000000000e-09	2.722500000000e+00	0.000000000000e+00	0.000000000000e+00	0.000000000000e+00	
```

**Comment by enocera** [comment]
Download theory 200, add the new FK tables to the relevant subfolder and upload theory 200 using the scritpt `upload_theories.sh` available in `apfelcomb/results'. You need the password for the CERN storage server, which is available [here](https://www.wiki.ed.ac.uk/display/nnpdfwiki/Storage+servers). If this makes you uncomfortable, just link the FK tables somewhere and I'll upload them for you.

**Comment by RoyStegeman** [comment]
Perfect, thanks!
