### ISSUE TITLE
Change LHAPDFSet to a python interface

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/nnpdf#1420]
Right now we use in many places in validphys some `LHAPDFSet` class. As far as I can see this can be substituted for a python interface (which lhapdf provides, so in practice what we are exchanging is the layer of libnnpdf that is calling the Cpp bindings of lhapdf).

Looks to me like a low-hanging fruit for the `destroyingc++` target.

Is there anything important I'm missing that would complicate this enormously?
I can work on this myself since I'm playing with the integration of nnpdf and pineappl and this is one of the sticking points*.

*not directly useful for the fit, but it makes the integration between validphys and pineappl more complicated where it shouldn't be

**Comment by Zaharid** [comment]
The most important missing functionality is 

https://github.com/NNPDF/nnpdf/blob/94428799a39a817e24b6ff0300c72467675be599/libnnpdf/wrapper/src/nnpdf.i#L140

I have some half backed implementation in Cython here. 

https://github.com/Zaharid/pylhapdf

In addition to that lhapdfset has some creative ideas in regards to how monte carlo sets should be indexed (basically discarding replica 0) and we would have  to go carefully over the code to make sure we are indexing properly.

**Comment by scarlehoff** [comment]
By "missing functionality" you mean doing those loops in python will be _slow_ I guess.
Since that loop is the only thing that could be problematic in python I don't think it'll be that dramatic (my goal is not to write the full thing as you did).

> In addition to that lhapdfset has some creative ideas in regards to how monte carlo sets should be indexed (basically discarding replica 0) and we would have to go carefully over the code to make sure we are indexing properly.

This will be tricky, luckily I think it should be easily testable (so difficult to do properly, but difficult to merge it broken as well).

**Comment by Zaharid** [comment]
> By "missing functionality" you mean doing those loops in python will be _slow_ I guess. Since that loop is the only thing that could be problematic in python I don't think it'll be that dramatic (my goal is not to write the full thing as you did).
> 

When I was testing it at some point, it *was* slow. But maybe we don't care that much any more....

**Comment by scarlehoff** [comment]
@Zaharid is there any document defining all the different error types defined inside the LHAPDFSet and its kinks (other than going through the code and noting it down...)

**Comment by Zaharid** [comment]
We only use three of those atm in practice. The better way may be to look starting from here:

https://github.com/NNPDF/nnpdf/blob/891bcc0c8b8ac710adb5c0ec7aa7c7df64080899/validphys2/src/validphys/core.py#L746
