### ISSUE TITLE
Tensorflow package for python 3.9

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#1458]
I finally got around trying to build the package with python 3.9 and `boa`. Instead of the horrible error messages in #1335 I now see something that looks like explaining the cause of the problem. I set the environment variable `CONDA_PY=39` and run `conda mambabuild conda-recipe` I get the error

```
Mamba failed to solve:
 - coverage
 - swig 3.0.10.*
 - pytest-mpl
 - sysroot_linux-64 2.17.*
 - pytest
 - hypothesis
 - cmake
 - gcc_linux-64
 - gxx_linux-64
 - opt_einsum >=2.3.2
 - gsl >=2.4,<2.5.0a0
 - gsl >=2.4,<2.5.0a0
 - sphinxcontrib-bibtex
 - libstdcxx-ng >=9.3.0
 - sphinx_rtd_theme >0.5
 - yaml-cpp >=0.6.3,<0.6.4.0a0
 - yaml-cpp >=0.6.3,<0.6.4.0a0
 - psutil
 - gast 0.3.3.*
 - pandas
 - python >=3.9,<3.10.0a0
 - blessings >=1.7
 - tensorflow >=2 *eigen*
 - requests
 - pkg-config
 - sphinx >=4.0.2
 - docutils 0.16.*
 - seaborn
 - prompt_toolkit
 - recommonmark
 - validobj
 - matplotlib >=3.3.0
 - libarchive >=3.4,<3.5.0a0
 - libarchive >=3.4,<3.5.0a0
 - hyperopt
 - numpy
 - scipy >=0.19.1
 - sqlite >=3.36.0,<4.0a0
 - libgcc-ng >=9.3.0
 - reportengine >=0.30.25
 - lhapdf >=6.4.0,<6.4.1.0a0
 - apfel >=3.0.5.0,<3.0.5.1.0a0

with channels:

The reported errors are:
   Encountered problems while solving:
     - package tensorflow-2.0.0-eigen_py36ha83d16c_0 requires tensorflow-base 2.0.0 eigen_py36h4ed9498_0, but none of the providers can be installed
```

which looks like it is saying that there is no "eigen" version that works.  Is there some other package that would work with python 3.9 without memory leaks and other known problems?

**Comment by Zaharid** [comment]
Incidentally I have the impression that #1284 would be an easy and quick win e.g. since it gave me this error in seconds rather than hours.

**Comment by RoyStegeman** [comment]
It might have something to do with the fact that we froze the `gast` version when preparing the 4.0 environment. Perhaps the tf versions that can use the frozen `gast==3.3.0` do not also support python 3.9. Though a quick look at dependencies makes me think it should have downloaded tf 2.4.1.

**Comment by Zaharid** [comment]
Right. Removing that pinning makes it work. But then I get some unrelated weird linking error for C++.

**Comment by RoyStegeman** [comment]
What error is that? If I do `conda mambabuild conda-recipe` with unpinned gast the issue I see is that some tests fail because cannot import curio.

**Comment by Zaharid** [comment]
The error I am seeing is

```
[100%] Linking CXX shared module _nnpdf.so
/home/zah/anaconda3/conda-bld/nnpdf_1635773379120/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lx86_64-conda-linux-gnu-gcc
collect2: error: ld returned 1 exit status
make[2]: *** [libnnpdf/wrapper/CMakeFiles/_nnpdf.dir/build.make:104: libnnpdf/wrapper/_nnpdf.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:253: libnnpdf/wrapper/CMakeFiles/_nnpdf.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

**Comment by RoyStegeman** [comment]
Hmm that's odd...

```
[100%] Linking CXX shared module _nnpdf.so
[100%] Built target _nnpdf
Consolidate compiler generated dependencies of target nnpdf
[ 44%] Built target nnpdf
[ 46%] Built target nnpdf_swig_compilation
Consolidate compiler generated dependencies of target _nnpdf
[ 51%] Built target _nnpdf
Consolidate compiler generated dependencies of target common
[ 64%] Built target common
Consolidate compiler generated dependencies of target chi2check
[ 68%] Built target chi2check
Consolidate compiler generated dependencies of target nnfit
[ 88%] Built target nnfit
Consolidate compiler generated dependencies of target evolven3fit
[100%] Built target evolven3fit
Install the project...
```

**Comment by RoyStegeman** [comment]
Did you also unpin sysroot by any chance?

**Comment by Zaharid** [comment]
I did not. Are you using mambabuild?

**Comment by RoyStegeman** [comment]
Yes I'm doing `conda mambabuild conda-recipe` on the master branch with gast unpinned and python 3.9

**Comment by Zaharid** [comment]
No idea then...

FWIW the curio issue might disappear by removing it from our repos. It is already up to date in conda forge.

**Comment by Zaharid** [comment]
If I try to do the same thing on another computer, it is picking the conda forge compilers, which  build fine. On my laptop it is picking the defaults ones, which is what I would expect given the channel orderings, and these break.

**Comment by scarlehoff** [comment]
I guess there's a solution for this https://github.com/NNPDF/nnpdf/pulls?q=is%3Apr+is%3Aopen+label%3Adestroyingc%2B%2B :P 

> If I try to do the same thing on another computer, it is picking the conda forge compilers, which build fine.

Which priority do you normally use / what's the priority in the other computer.

I guess nnpdf > conda-forge > default in the one that works? Besides being from default or conda-forge, is there a difference in the versions you get?

**Comment by Zaharid** [comment]
Strangely in both cases I have defaults before conda forge (as done in binary bootstrap). I don't know why it picks the conda forge compilers that work.

**Comment by scarlehoff** [comment]
Doing some tests, if I install `boa` inside a conda environment with nnpdf, it uses `conda-forge` but instead if I use a fresh conda environment (to be safe I redownloaded miniconda and everything), it uses default. I guess there's some non-trivial dependency mess.

**Comment by scarlehoff** [comment]
If we go for this solution: https://github.com/NNPDF/nnpdf/pull/1460#issuecomment-957974236 we need to commit to it.
On the other hand, we might want to start removing the parts of libNNPDF that we don't need so that we can lighten up the build and host dependencies.

**Comment by scarlehoff** [comment]
Ok, problem found:

https://github.com/NNPDF/nnpdf/blob/36da775cf0ae921c57f12bec4ca3da4ac30c0d82/libnnpdf/wrapper/CMakeLists.txt#L33

The split " " makes the compiler into a library and then conda doesn't find it anymore. All the bugs just needed a `strip()` in the right place :)
