### ISSUE TITLE
Buildmaster runtime issue 2

### ISSUE THREAD

**Issue by J-M-Moore** [NNPDF/nnpdf#1462]
Fixing the problem in the previous buildmaster issue, I now get the error:

```
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: CommonData::Verify failed for set NMCPD_dw_ite
Abort trap: 6
```

**Comment by enocera** [comment]
Weird, buildmaster compiles and executes just fine on my laptop, let me check on another machine and see what's wrong with `NMCPD`.

**Comment by Zaharid** [comment]
I cannot reproduce this either unfortunately. But would bet it indicates a bug somewhere.

**Comment by enocera** [comment]
@Zaharid Indeed - that's why I'm looking into `NMCPD`.
