### ISSUE TITLE
Add tutorial on computing chi²

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#1478]
The way we use and define objective functions and chi² related metrics has many knobs, which makes it difficult to use and interpret correctly without a lot of context. It would be good to have a tutorial that lists the possible options, their applications and the relevant vp flags.

These are at least:

  - t0
  - use_pdferror
  - regularization
  - weights

**Comment by RoyStegeman** [comment]
Pretty sure at least some of these are defined in the docs where they are relevant. So just to be clear, is your idea to make a separate page collecting all of them in a single page and just have the info in the docs twice, and/or cross referencing the places where they are already discussed?

I agree that, now that there are external users, such a page might be useful.

**Comment by Zaharid** [comment]
Yes indeed. It seems clear that having a page that can be referenced in one go would be useful.
