### ISSUE TITLE
Improve postfit error message

### ISSUE THREAD

**Issue by J-M-Moore** [NNPDF/nnpdf#1479]
Currently when trying to run postfit on new fits naively, the error message:

```
[WARNING]: Cannot find info file at /rds/user/jmm232/hpc-work/nnpdf_dev_install/top_fits/no_top_fit/nnfit/no_top_fit.info
[ERROR]: Error in postfit:
Postfit cannot find a valid LHAPDF info file
```

is given. It would be useful if this error message was more descriptive and pointed to the appropriate tutorial in the docs.

**Comment by scarlehoff** [comment]
What would be an example of a more descriptive error? The relevant line is
https://github.com/NNPDF/nnpdf/blob/eeae19b15c960b4f8f974c3ac2ba2af36ed845bc/validphys2/src/validphys/scripts/postfit.py#L143
If you want to give it a go. I guess a link to [this](https://docs.nnpdf.science/tutorials/run-fit.html) with "making sure all steps were successful" or something would work, however at that point `postfit` does not know why that `info` file is missing so it could potentially guide the user in the wrong direction (although most of the time `apfel` has probably not been run).
