### ISSUE TITLE
Checking replica 0 in different PDF sets

### ISSUE THREAD

**Issue by enocera** [NNPDF/nnpdf#1496]
I claim the following:
1. that replica 0 in the `referee_nnpdf40_replicas` set is identical to replica 0 in the compressed set `NNPDF40_nnlo_as_01180`
2. that replica0 in the compressed set is not identical to replica 0 in the 1000 replica set `NNPDF40_nnlo_as_01180_1000`

@Zaharid do you agree with these two claims or not?
I understand that @Zaharid claims that replica 0 in the `NNPDF40nnAlt` set (which I cannot access) is also identical to replica 0 in the `referee_nnpdf40_replicas` set. Is my understanding correct? If so, shouldn't you get the same output if you run this runcard
https://vp.nnpdf.science/BgVzbNV-TnCI2kJmG7k2qg==/input
or an identical runcard in which `NNPDF40nnAlt` is replaced by `referee_nnpdf40_replicas`?

**Comment by Zaharid** [comment]
> I claim the following:
> 
>     1. that replica 0 in the `referee_nnpdf40_replicas` set is identical to replica 0 in the compressed set `NNPDF40_nnlo_as_01180`

No, that is the same as the 1000 replica set.

> 
>     2. that replica0 in the compressed set is not identical to replica 0 in the 1000 replica set `NNPDF40_nnlo_as_01180_1000`
> 

That is correct.


> 
> @Zaharid do you agree with these two claims or not? I understand that @Zaharid claims that replica 0 in the `NNPDF40nnAlt` set (which I cannot access) is also identical to replica 0 in the `referee_nnpdf40_replicas` set. Is my understanding correct?

No it isn't: replica 0 for `referee_nnpdf40_replicas` is the 1000 set.
replica0 for `NNPDF40nnAlt` (which we should forget about) is the 100 set

 If so, shouldn't you get the same output if you run this runcard https://vp.nnpdf.science/BgVzbNV-TnCI2kJmG7k2qg==/input or an identical runcard in which `NNPDF40nnAlt` is replaced by `referee_nnpdf40_replicas`?

See above.

**Comment by Zaharid** [comment]
sorry for the confusion with all this, btw.

**Comment by enocera** [comment]
> No it isn't: replica 0 for `referee_nnpdf40_replicas` is the 1000 set. replica0 for `NNPDF40nnAlt` (which we should forget about) is the 100 set

OK, then I'll try a clean download of the pdf sets, because by no means I see how replica0 for `referee_nnpdf40_replicas` is the 1000 set. I agree that we should forget about NNPDF40nnAlt.

The only reason I insist about clarifying where replica0 comes from is to check whether the difference between replica0 in the 1000 set and in the compressed set is such to lead to the large variation of chi2 that you observe (and that I don't).

And BTW, no need to apologise - this is the typical case where things can go wrong. If we hadn't validphys and if we hadn't a repository, all these checks would be enormously more complicate. So certainly you deserve to be thanked, you don't need to apologise.

**Comment by enocera** [comment]
@Zaharid I'm sorry to insist, but this is what I get after a fresh download of the PDF sets using vp. Just to check that we are looking at the same files, here's line 7 of `*0000.dat` for
- `NNPDF40_nnlo_as_01180_1000`
```
0.0000000E+00 -1.6131341E-01  1.4221297E+00  1.4233316E+00  1.4229196E+00  2.1962101E-01  1.4233225E+00  1.4237345E+00  1.4218089E+00 -1.6131340E-01  0.0000000E+00
```
- referee_nnpdf40_replicas
```
0.0000000E+00 -1.6904794E-01  1.4240670E+00  1.4253536E+00  1.4249977E+00  1.4844111E-01  1.4254154E+00  1.4257712E+00  1.4236875E+00 -1.6904794E-01  0.0000000E+00
```
- `NNPDF40_nnlo_as_01180`
```
0.0000000E+00 -1.6904794E-01  1.4240670E+00  1.4253536E+00  1.4249977E+00  1.4844111E-01  1.4254154E+00  1.4257712E+00  1.4236875E+00 -1.6904794E-01  0.0000000E+00
```
A diff confirms that `referee_nndf40_replicas` and `NNPDF40_nnlo_as_01180` are identical. The `NNPDF40_nnlo_as_01180_1000` and `NNPDF40_nnlo_as_01180` PDF sets downloaded with vp are identical to those downloaded with LHAPDF.

**Comment by Zaharid** [comment]
> @Zaharid I'm sorry to insist, but this is what I get after a fresh download of the PDF sets using vp. Just to check that we are looking at the same files, here's line 7 of `*0000.dat` for
> 
>     * `NNPDF40_nnlo_as_01180_1000`
> 
> 
> ```
> 0.0000000E+00 -1.6131341E-01  1.4221297E+00  1.4233316E+00  1.4229196E+00  2.1962101E-01  1.4233225E+00  1.4237345E+00  1.4218089E+00 -1.6131340E-01  0.0000000E+00
> ```
> 
>     * referee_nnpdf40_replicas
> 
> 
> ```
> 0.0000000E+00 -1.6904794E-01  1.4240670E+00  1.4253536E+00  1.4249977E+00  1.4844111E-01  1.4254154E+00  1.4257712E+00  1.4236875E+00 -1.6904794E-01  0.0000000E+00
> ```
> 
>     * `NNPDF40_nnlo_as_01180`
> 
> 
> ```
> 0.0000000E+00 -1.6904794E-01  1.4240670E+00  1.4253536E+00  1.4249977E+00  1.4844111E-01  1.4254154E+00  1.4257712E+00  1.4236875E+00 -1.6904794E-01  0.0000000E+00
> ```
> 
> A diff confirms that `referee_nndf40_replicas` and `NNPDF40_nnlo_as_01180` are identical. The `NNPDF40_nnlo_as_01180_1000` and `NNPDF40_nnlo_as_01180` PDF sets downloaded with vp are identical to those downloaded with LHAPDF.

Ok, I agree with all this, contrary to what I had said.

**Comment by enocera** [comment]
@Zaharid Thank you very much for checking. Then I don't know where the much lower numbers for the chi2 of replica0 in your original report https://vp.nnpdf.science/BgVzbNV-TnCI2kJmG7k2qg==/ come from. The only reason I wonder is because we are looking for a PDF (or PDF replica) with chi2<chi20, and it seems that, at least in your report, such a PDF exists. Otherwise I'm perfectly happy to forget about it.

**Comment by Zaharid** [comment]
If I repeat the report with the `NNPDF40nnAlt` I have on my computer I reproduce everyone's results. I have no idea how my original report was done.

**Comment by enocera** [comment]
Fine. I think that, with this, I can close this issue and we can forget about those lower numbers.
