### ISSUE TITLE
Add vp parser for new commondata format

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#1511]
We would like to take the input in #1500 and write a parser that results in essentially coredata.Commondata,
https://github.com/NNPDF/nnpdf/blob/ab7f0536cc471bbc53ed6c107ab93a96f7c3dd02/validphys2/src/validphys/coredata.py#L123

with a few adjustments such as supporting n kinematics.

That should come with the accompanying machinery for Loader. We are going to have some more context dependent options, such as the relevant variant that gets selected.

**Comment by scarlehoff** [comment]
Superseded by #1709
