### ISSUE TITLE
Change MC PDFs to return all members + CV when queried ?

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/nnpdf#1516]
At the moment when we query Hessian PDF we get results for all members in the lhapdfset, instead for MC PDFs we return the error members and only get the central value when asking explicitly for it.

Then, in the `Stats` class, when querying MC PDFs when you query the error members you get all members (because that's the only thing you got anyway) and when querying Hesssian PDFs you get all but member one. That's ok...

However, this introduces inconsistencies in several places (or maybe they are not?... I'm very confused about this!)

Take for instance the arclength calculation: https://github.com/NNPDF/nnpdf/blob/0160b267a7e29da9fca97965a233e17347e75140/validphys2/src/validphys/arclength.py#L31

there, in line 53 (`#PDF evaluated on grid`) the grid values are used. This includes the central value for Hessian PDFs but not for MC PDFs. Is that correct? (why?) 
Is it correct just by chance because later on we are using the `Stats` class and then that extra replica that was computed is effectively forgotten forever?

(cc @Zaharid @enocera )

I need an answer to that so that in #1515 I can use `error_members()` where it makes sense instead of going for the raw `.data` (which mind you, makes sense sometimes)

**Comment by Zaharid** [comment]
> Then, in the `Stats` class, when querying MC PDFs when you query the error members you get all members (because that's the only thing you got anyway) and when querying Hesssian PDFs you get all but member one. That's ok...

You mean the other way around?

In the arclegth computation we want to return "everything that matters in the right order" which we are passing to an object  is of type pdf.stats_class itself. I think we concluded that that should now mean also replica zero for montecarlo. Whether the property should still be called error_members is a related but different matter....

**Comment by scarlehoff** [comment]
The problem is that the arclength (and the same happens in other places) right now uses the error_members for MC PDF and the full set of members for hessian PDFs.

Later on the stats class is used so I guess the right thing is done but internally it is inconsistent.

**Comment by Zaharid** [comment]
It is simply that we used to never load replica zero for mc sets, no?

**Comment by scarlehoff** [comment]
Yes, which means that using the raw grid values data means different things depending on the representation. It doesn't matter when the `Stats` class is used, but that's not always the case.

**Comment by scarlehoff** [comment]
The sumrules are also computed "wrong" (or inconsistently) for Hessian PDFs: 
https://github.com/NNPDF/nnpdf/blob/9840fc69dfcbcf25ebb30236916c4f1fc65a1785/validphys2/src/validphys/sumrules.py#L128

I'm listing here all things that look buggy or inconsistent to me, but tbh most (all) of them have no effect on the final results because either they are wrapped in `Stats` classes somewhere down the line (which can be a problem if everything is a `Stats` class) or they are situations where it doesn't really matter (like in the sum rules, by definition the central value will be inside the envelope so it doesn't matter that it is computed differently for MC and Hessian PDFs).
