### ISSUE TITLE
Have we run out of space on vp.nnpdf.science?

### ISSUE THREAD

**Issue by enocera** [NNPDF/nnpdf#1523]
While trying to upload a fit, I receive this error message
```
[INFO]: Uploading output (/data/theorie/enocera/nnpdfgit/fits/fit_upload_deleteme_aeauekvj) to nnpdf@vp.nnpdf.science
rsync: write failed on "/home/nnpdf/WEB/fits/NNPDF40_nnlo_as_01300_corr_s1.tar.gz": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(393) [receiver=3.1.2]
```

**Comment by enocera** [comment]
OK, thanks. I'll close the issue tomorrow, then.

**Comment by enocera** [comment]
This seems to be solved, indeed. Thanks.

**Comment by enocera** [comment]
So, yesterday everything was working, today nothing is working anymore. ??

**Comment by siranipour** [comment]
I think Zahari deleted only a few packages and so it was a temporary fix

On 19 Feb 2022, at 10:37, Emanuele R. Nocera ***@***.***> wrote:

﻿

So, yesterday everything was working, today nothing is working anymore. ??

**Comment by enocera** [comment]
I see, thanks.

**Comment by RoyStegeman** [comment]
What's the status on this?

**Comment by scarrazza** [comment]
We had to setup a new machine. It is online, however the server/cert must be setup properly.

**Comment by enocera** [comment]
@scarrazza Maybe I misunderstood the discussion yesterday, I had the feeling that the new machine is on and working, but that some reshuffling of the material which is public and which is not is being undertaken. If I try to upload a fit, I get this error
```
rsync: mkdir "/home/nnpdf/WEB/fits" failed: No such file or directory
```
Are any amendments to `nnprofile.yaml.in` required?

**Comment by scarrazza** [comment]
Please retry now, I have included a link to the folder so we don't have to touch the code.

**Comment by enocera** [comment]
Thanks. One weird thing: I continue receiving the message
```
[ERROR]: The object is uploaded but hasn't been indexed yet by the server. You should upload it again to ensure it is indexed: vp-upload 220219-ern-005
```
even after the third consecutive attempt. When the indexing failed the first time, it used to go fine the second time.

**Comment by Zaharid** [comment]
@scarrazza  seems to me the commands in crontab are referencing to scripts that don't exist.

**Comment by scarrazza** [comment]
@Zaharid, could you please check if crontab looks ok now?

**Comment by enocera** [comment]
Everything seems to work fine on my side.

**Comment by Zaharid** [comment]
@scarrazza Is there some weird firewall installed? I started randomly getting connection refused in the middle of uploading the reports.

**Comment by scarlehoff** [comment]
There is some problem with `rssh` https://github.com/NNPDF/nnpdf/runs/5333478781?check_suite_focus=true#step:8:15

**Comment by RoyStegeman** [comment]
When I try to upload a fit it still isn't indexed. Given that it worked for Emanuelle has something changed in the meantime?

**Comment by Zaharid** [comment]
rssh is only used by the CI afaict.

**Comment by RoyStegeman** [comment]
Any idea why it doesn't index when I upload, but it does for Emanulle? Once the zipped folder is on the serve (which it is) it's just up to this `asyncwatch`  to add the name to the .json index list, right?

**Comment by scarlehoff** [comment]
> Any idea why it doesn't index when I upload, but it does for Emanuele? Once the zipped folder is on the serve (which it is) it's just up to this `asyncwatch` to add the name to the .json index list, right?

@scarrazza I don't think the jobs for the indexing have been started?

**Comment by Zaharid** [comment]
It may be that it never indexes automatically. I did run it once manually to test. @scarrazza maybe the cron scripts have to be started once.

**Comment by Zaharid** [comment]
I am reopening this as there are still important things broken. For one package uploading is still not working.

**Comment by enocera** [comment]
But then shouldn't we open a new issue with another title? Anyway, whatever you prefer is fine.

**Comment by Zaharid** [comment]
Part of the thinking is that if there was an issue for everything that has been broken, that would be a lot of issues…

**Comment by Zaharid** [comment]
Problems I am finding:

 - [ ] The package uploads (afaict the /etc/rssh.conf file is missing).
 - [ ] Access control.
 - [ ] The data folder changes should be reflected in the documentation and vp server scripts (the docs could use some update).

**Comment by scarrazza** [comment]
@Zaharid could you please retry now? I have restored the old system layout, no more /data folder.

**Comment by Zaharid** [comment]
@scarrazza I unticked the access control bullet as I still see problems with that.

**Comment by scarrazza** [comment]
Well, I don't think we can do much for access control the new server is under the staff-IT responsibility, so access with admin privileges are restricted by university policy.

**Comment by Zaharid** [comment]
Please see email.
