### ISSUE TITLE
different flavourmap for jet data of different alphas theories

### ISSUE THREAD

**Issue by RoyStegeman** [NNPDF/nnpdf#1527]
As said during the meeting, the FK tables corresponding to the jet datasets don't have the same grid sizes and thus it's causing some trouble with the alphas fit. I was wrong about it being related to the xgrid though as it turns out it's related to the flavourmap. The code snippet below can be run to check that the flavour maps are not the same.

Is this expected?

```
from validphys.fkparser import load_fktable
from validphys.loader import Loader
l = Loader()

fk = l.check_fktable(setname="CMS_1JET_8TEV", theoryID=200, cfac=('QCD',))
res = load_fktable(fk)
flavmap200 = res.metadata['FlavourMap']

fk = l.check_fktable(setname="CMS_1JET_8TEV", theoryID=201, cfac=('QCD',))
res = load_fktable(fk)
flavmap201 = res.metadata['FlavourMap']

print(flavmap200 == flavmap201)
```

**Comment by enocera** [comment]
Thanks. I'll investigate. Is `CMS_1JET_8TEV` the only offending dataset? Can you please list all of the datasets that share the same issue? Thanks.

**Comment by RoyStegeman** [comment]
Out of the NNPDF4.0 datasets the following have this issue:
- ATLAS_2JET_7TEV_R06
- ATLAS_1JET_8TEV_R06_DEC
- CMS_2JET_7TEV
- CMS_1JET_8TEV

**Comment by enocera** [comment]
Very good, thanks. I'll come back to you as soon as possible. I expect the flavour map to be the same across all theories, so this surely requires investigation.

**Comment by RoyStegeman** [comment]
Thanks. In fact, also for the integrability dataset the fkspecs are not exactly the same. Here the xgrids differ in some cases as can be confirmed using the snippet below. 

```
    ds = API.posdatasets(
        posdatasets=[{"dataset": dataset, "maxlambda": 1e2}],
        theoryid=200
    )
    res = load_fktable(ds[0].fkspecs[0])
    xgrid0 = res.xgrid.shape
    

    ds = API.posdatasets(
        posdatasets=[{"dataset": dataset, "maxlambda": 1e2}],
        theoryid=201
    )
    res = load_fktable(ds[0].fkspecs[0])
    xgrid1 = res.xgrid.shape
```

**Comment by enocera** [comment]
@RoyStegeman just to mention that I've possibly identified the issue and I'll update the theories soon.

**Comment by enocera** [comment]
@RoyStegeman I've looked into this a little. I've recomputed the FK tables for the offending data sets but this does not solve the issue. Let's try to proceed incrementally. Let's consider `CMS_2JET_7TEV` and theories 200, 201, 202, 203, 204, 205, 206, 207, 233, 234, 235, 236 and 239. What I find is that all theories have the same flavour map, except 201 and 233, which share a flavour map which is different from that of all of the other theories. Can you please double check this? Unfortunately, the pattern of discrepancies seem different for other data sets.

**Comment by RoyStegeman** [comment]
Sure, I'll have to download all these theories which will take a while, but I'll produce a matrix of cases where these flavour maps differ and where they are the same.

Actually, already for theories 200 and 201 I find that the flavor maps are not the same. This is the corresponding boolean matrix of which indices of the flavour maps agree:
```
  1   1   1   1   1   1   1   1   1   1   1   1   1   1
  1   1   1   1   1   1   1   1   1   1   0   1   1   1
  1   1   1   1   1   1   1   1   1   1   0   1   1   1
  1   1   1   1   1   1   1   1   1   1   1   1   1   1
  1   1   1   1   1   1   1   1   1   1   1   1   1   1
  1   1   1   1   1   1   1   1   1   1   1   1   1   1
  1   1   1   1   1   1   1   1   1   1   1   1   1   1
  1   1   1   1   1   1   1   1   1   1   1   1   1   1
  1   1   1   1   1   1   1   1   1   1   1   1   1   1
  1   1   1   1   1   1   1   1   1   1   1   1   1   1
  1   0   0   1   1   1   1   1   1   1   1   0   1   1
  1   1   1   1   1   1   1   1   1   1   0   1   1   1
  1   1   1   1   1   1   1   1   1   1   1   1   1   1
  1   1   1   1   1   1   1   1   1   1   1   1   1   1

```

**Comment by RoyStegeman** [comment]
Here it is. 201 and 233 indeed seem to be the theories different from all the others. 

```
    200 201 202 203 204 205 206 207 233 234 235 236 239
200   1   0   1   1   1   1   1   1   0   1   1   1   1
201   0   1   0   0   0   0   0   0   1   0   0   0   0
202   1   0   1   1   1   1   1   1   0   1   1   1   1
203   1   0   1   1   1   1   1   1   0   1   1   1   1
204   1   0   1   1   1   1   1   1   0   1   1   1   1
205   1   0   1   1   1   1   1   1   0   1   1   1   1
206   1   0   1   1   1   1   1   1   0   1   1   1   1
207   1   0   1   1   1   1   1   1   0   1   1   1   1
233   0   1   0   0   0   0   0   0   1   0   0   0   0
234   1   0   1   1   1   1   1   1   0   1   1   1   1
235   1   0   1   1   1   1   1   1   0   1   1   1   1
236   1   0   1   1   1   1   1   1   0   1   1   1   1
239   1   0   1   1   1   1   1   1   0   1   1   1   1
```

**Comment by enocera** [comment]
As I mentioned, the pattern of discrepancies is different data set by dataset: if you were to compute the same matrix for other data sets, you'll find differences elsewhere (not only for theories 201 and 233).

**Comment by RoyStegeman** [comment]
I see, have you been able to understand why the discrepancies are there?

**Comment by enocera** [comment]
No - I had hoped to see some common pattern across all data sets, but this is not the case.

**Comment by RoyStegeman** [comment]
@enocera regarding the xgrid of the integ dataset (see https://github.com/NNPDF/nnpdf/issues/1527#issuecomment-1044860504). Only the xgrid of theory 200 deviates from the others. Do you know why this is? And perhaps more importantly, how to fix it?

**Comment by enocera** [comment]
This is fixed by regenerating the tables (a different number of points was used for theory 200). Actually, I've already re-generated these, let me update the theory on the server.

**Comment by RoyStegeman** [comment]
That's very helpful. Thanks

**Comment by enocera** [comment]
@RoyStegeman I've just updated the integrability FK tables in theory 200. Can you please try it again?

**Comment by RoyStegeman** [comment]
Thanks, let me try. It might take a while with the internet at the department...

**Comment by RoyStegeman** [comment]
That seemed to do the trick! Thanks!

**Comment by enocera** [comment]
Very good. Jets will follow soon-ish.

**Comment by RoyStegeman** [comment]
Excellent. With that we should have everything to do a full NNPDF4.0 fit with alphas so hopefully that resolves the peculiarities present in the current pdf+alphas fit.

**Comment by enocera** [comment]
Meanwhile I think that all the ingredients are there to perform the NNPDF3.1-like pdfs+alphas fits in order to make a one-to-one comparison with the correlated replica results (jets do not seem to have any problem there).

**Comment by RoyStegeman** [comment]
Unfortunately that's not going to be possible either. Theory 239 doens't contain ATLAS1JET11_NEW_SCALE, so that's why it's not included in the table below, but as you can see the flavormasks differ considerably between theories also for the NNPDF3.1-like jet datasets. 

```--------------------------------------------------------------
ATLAS1JET11_NEW_SCALE:
999 200 201 202 203 204 205 206 207 233 234 235 236
200   1   1   1   1   1   1   0   1   0   1   1   1
201   1   1   1   1   1   1   0   1   0   1   1   1
202   1   1   1   1   1   1   0   1   0   1   1   1
203   1   1   1   1   1   1   0   1   0   1   1   1
204   1   1   1   1   1   1   0   1   0   1   1   1
205   1   1   1   1   1   1   0   1   0   1   1   1
206   0   0   0   0   0   0   1   0   0   0   0   0
207   1   1   1   1   1   1   0   1   0   1   1   1
233   0   0   0   0   0   0   0   0   1   0   0   0
234   1   1   1   1   1   1   0   1   0   1   1   1
235   1   1   1   1   1   1   0   1   0   1   1   1
236   1   1   1   1   1   1   0   1   0   1   1   1


--------------------------------------------------------------
CMSJETS11_NEW_SCALE:
999 200 201 202 203 204 205 206 207 233 234 235 236
200   1   0   1   0   0   0   0   0   0   0   0   0
201   0   1   0   0   0   0   0   0   0   0   0   0
202   1   0   1   0   0   0   0   0   0   0   0   0
203   0   0   0   1   0   0   1   0   0   1   0   0
204   0   0   0   0   1   1   0   0   0   0   0   1
205   0   0   0   0   1   1   0   0   0   0   0   1
206   0   0   0   1   0   0   1   0   0   1   0   0
207   0   0   0   0   0   0   0   1   1   0   0   0
233   0   0   0   0   0   0   0   1   1   0   0   0
234   0   0   0   1   0   0   1   0   0   1   0   0
235   0   0   0   0   0   0   0   0   0   0   1   0
236   0   0   0   0   1   1   0   0   0   0   0   1

``` 


<details>
  <summary>Code snippet</summary>
  
```
import numpy as np

from validphys.api import API
from validphys.loader import FallbackLoader
l = FallbackLoader()

theoryids = [
    200,
    201,
    202,
    203,
    204,
    205,
    206,
    207,
    233,
    234,
    235,
    236,
    # 239
]

n_theories = len(theoryids)
agreement_matrix = np.ones((n_theories,n_theories), dtype=int)*5

setnames=[
    "ATLAS1JET11_NEW_SCALE",
    "CMSJETS11_NEW_SCALE",
]

with open("theory_xgrids.txt", 'w') as f:
    f.write("")

for setname in setnames:
    for i, theory_i in enumerate(theoryids):
        for j, theory_j in enumerate(theoryids):

            if i < j:

                fk1 = l.check_fktable(setname=setname, theoryID=theory_i, cfac=("QCD",))
                fk1_property = fk1.load().get_flmap()

                fk2 = l.check_fktable(setname=setname, theoryID=theory_j, cfac=("QCD",))
                fk2_property = fk2.load().get_flmap()

                if fk1_property.shape == fk2_property.shape:
                    agreement_matrix[i,j] = np.array(fk1_property != fk2_property).sum()==0
                else:
                    agreement_matrix[i,j] = False
            elif i==j:
                agreement_matrix[i,j] = True

            else:
                agreement_matrix[i,j] = agreement_matrix[j,i]

    index_names = np.array(theoryids)
    add_labels = np.ones((n_theories+1,n_theories+1))*999
    add_labels[0,1:] = index_names
    add_labels[1:,0] = index_names
    add_labels[1:,1:] = agreement_matrix

    #if (agreement_matrix == 0).sum() == 0:
    #    add_labels = np.array([222])

    with open("theory_xgrids.txt", "ab") as f:
        between_line = f"\n\n--------------------------------------------------------------\n{setname}:\n"
        byte_object = str.encode(between_line)
        f.write(byte_object)
        np.savetxt(f, add_labels, fmt="%3u")



```
</details>

**Comment by enocera** [comment]
Ah really? I thought I had checked last week, let me re-check again!

**Comment by enocera** [comment]
You can ignore theory 239 for the time being, this is for alphas=0.130 and this has never been used so far.

**Comment by RoyStegeman** [comment]
@enocera did you manage to conclude the NNPDF3.1-like jet datasets? If so, I can probably get some results before the PC tomorrow.

**Comment by enocera** [comment]
@RoyStegeman I'm working on this RIGHT NOW.

**Comment by enocera** [comment]
It's taking longer than what I anticipated yesterday, it's unlikely that we will be able to have results by tomorrow.

**Comment by enocera** [comment]
I'm almost there - hopefully I'll be able to update the FK tables for `ATLAS1JET11_NEW_SCALE` or `CMSJETS11_NEW_SCALE` by midnight.

**Comment by RoyStegeman** [comment]
Okay just let me know when they're done (if you're still awake / at your pc for it), I might be able to start a fit tonight and get a sample of replicas by the morning.

**Comment by enocera** [comment]
@RoyStegeman I've just finished to upload theories 200-207 and 233-236 with the fixed FK tables for `ATLAS1JET11_NEW_SCALE` and `CMSJETS11_NEW_SCALE`. Here is what I obtain using the fixed FK tables:
```
--------------------------------------------------------------
ATLAS1JET11_NEW_SCALE:
999 200 201 202 203 204 205 206 207 233 234 235 236
200   1   1   1   1   1   1   1   1   1   1   1   1
201   1   1   1   1   1   1   1   1   1   1   1   1
202   1   1   1   1   1   1   1   1   1   1   1   1
203   1   1   1   1   1   1   1   1   1   1   1   1
204   1   1   1   1   1   1   1   1   1   1   1   1
205   1   1   1   1   1   1   1   1   1   1   1   1
206   1   1   1   1   1   1   1   1   1   1   1   1
207   1   1   1   1   1   1   1   1   1   1   1   1
233   1   1   1   1   1   1   1   1   1   1   1   1
234   1   1   1   1   1   1   1   1   1   1   1   1
235   1   1   1   1   1   1   1   1   1   1   1   1
236   1   1   1   1   1   1   1   1   1   1   1   1


--------------------------------------------------------------
CMSJETS11_NEW_SCALE:
999 200 201 202 203 204 205 206 207 233 234 235 236
200   1   1   1   1   1   1   1   1   1   1   1   1
201   1   1   1   1   1   1   1   1   1   1   1   1
202   1   1   1   1   1   1   1   1   1   1   1   1
203   1   1   1   1   1   1   1   1   1   1   1   1
204   1   1   1   1   1   1   1   1   1   1   1   1
205   1   1   1   1   1   1   1   1   1   1   1   1
206   1   1   1   1   1   1   1   1   1   1   1   1
207   1   1   1   1   1   1   1   1   1   1   1   1
233   1   1   1   1   1   1   1   1   1   1   1   1
234   1   1   1   1   1   1   1   1   1   1   1   1
235   1   1   1   1   1   1   1   1   1   1   1   1
236   1   1   1   1   1   1   1   1   1   1   1   1
```
which is evidence that the flavour map is consistent across all of the theories. 
In order to fix the flavour map, I've considered alternatively a) the intersection or b) the union of the flavour maps of the various grids or c) the flavour map of any of the theories and it seems that predictions remain the same irrespective of a), b) or c). For instance here are the values of the chi2, computed with `NNPDF40_nnlo_as_01180`:
- with the FK tables BEFORE the fix https://vp.nnpdf.science/kpx1sgxXRmKSFv6FODRbGA==
- with the FK tables AFTER the fix (considering the intersection) https://vp.nnpdf.science/YFHXsUoPQnGp6AXtqzyP6g==

I'd say that this confirms the conjecture that the flavour map is accidentally different, most likely because of an imperfect tuning of the threshold that activates a specific PDF channel or not.

Be that as it may, if you download again the relevant theories, you should be able to run a Simunet fit for the NNPDF3.1-like case, actually for all of the three variations considered in the last three tables at this page https://www.wiki.ed.ac.uk/pages/viewpage.action?spaceKey=nnpdfwiki&title=Correlated+replica+method. I suggest to download the theories and check independently that all the theories have now the same flavour map before launching a fit, just to make sure that I didn't mess up with the upload. Note that the correlated replica fits do not use all of the theories above (in particular they do not use theories 203, 204 and 206 which correspond to 0.0005 increments of alphas). As I said, I'll fix the remaining jet data over the week-end.

**Comment by RoyStegeman** [comment]
Thanks for this great work! I'll start downloading the theories now, but I imagine I'll not perform any checks before tomorrow morning.

These are very comforting results, the fact that the chi2 values corresponding to taking the intersection perfectly agrees with the BEFORE results indeed means we can proceed without the need to worry about how this affects the results of a fit.

**Comment by enocera** [comment]
And of course if it doesn't work, please complain!

**Comment by RoyStegeman** [comment]
Of ocurse, thanks. 

Just FYI: last night, as a test, I tried running a small fit with few datsets -- but including the two jet datasets -- and it was able to run the fit. So at least for theories 200, 201 and 202 the problem has been solved! Then I started the fulll NNPDF3.1-like fit also using the full range of theories, and for some reason it gave all NaNs for the losses, though it no longer complained about the flavor map. I hope this is just the result of some mistake by me which can quickly be resulved.

**Comment by RoyStegeman** [comment]
Is it possible something changed about `DYE886R` (at least for theory 200, not for 201 or 202, don't know about the others)? Because with the "old" (pre your chaanges) FK tables I am able to fit this dataset, but there are of course the problems with the jets and integ datasets. Using the most recent FK tables I am able to run an NNPDF3.1-like fit without `DYE886R` , but if it is included I either get an unhelpful error message, or it finds very large values for the corresponding experimental chi2 and nans for the validation loss.

**Comment by enocera** [comment]
In principle nothing should have changed, BUT let me check.

**Comment by RoyStegeman** [comment]
Thanks

**Comment by RoyStegeman** [comment]
Do you think that I just use the old FK table in the meantime?

**Comment by enocera** [comment]
yes, definitely.

**Comment by RoyStegeman** [comment]
Okay, in that case I will replace the problematic theory 200 DYE886R FK tables with the old versions (while the other FK tables are the most recent version downloaded last night) and start the fit. With that it should be possible to do the fit.

**Comment by enocera** [comment]
Hi @RoyStegeman just to mention that I'm behind schedule (as usual), I'll hopefully fix the remaining jet FK tables by the end of the day.

**Comment by RoyStegeman** [comment]
@enocera no worries, at this time we have the one-to-one comparison for NNPDF3.1 (you may have seen the email I sent?) and there are already some things to be understood about that situation. Of course it would be nice to see if we observe similar features when fitting the NNPDF4.0 dataset (larger spread in alphas, smaller overall, larger gluon uncertainty...), but since we have the NNDPF3.1 fit there is a bit less pressure to quickly get 4.0 as well.

**Comment by enocera** [comment]
@RoyStegeman I'm about to uploading the FK tables for all of the jet data with a consistent flavour map. I'd like to fix the problem with `DYE886R` at the same time. What are the affected theories? 200 only?

**Comment by RoyStegeman** [comment]
Of the theories that I am using the only problematic theory is indeed theory 200. Also, as said, the problem was only introduced after the last update of the FK tables in the theory, so I don't believe that at this point there's really any reason to think other theories would have this problem. 

I'm currently redownloading the theory locally to see if I can still reproduce the error, but that will take a while (even if the internet does not disconnect halfway through downloading...)

**Comment by enocera** [comment]
Thanks. No need to download anything for the time being. Let me update the jet data first.

**Comment by enocera** [comment]
Here we are. I've finally updated all the alphas theories (200-207; 233-236) in such a way that all the jet data sets have a consistent flavour map across theories. I've also (hopefully) fixed the inconsistency with the `DYE886R` in theory 200.
Here is the output of the check code
```
--------------------------------------------------------------
ATLAS_2JET_7TEV_R06:
999 200 201 202 203 204 205 206 207 233 234 235 236
200   1   1   1   1   1   1   1   1   1   1   1   1
201   1   1   1   1   1   1   1   1   1   1   1   1
202   1   1   1   1   1   1   1   1   1   1   1   1
203   1   1   1   1   1   1   1   1   1   1   1   1
204   1   1   1   1   1   1   1   1   1   1   1   1
205   1   1   1   1   1   1   1   1   1   1   1   1
206   1   1   1   1   1   1   1   1   1   1   1   1
207   1   1   1   1   1   1   1   1   1   1   1   1
233   1   1   1   1   1   1   1   1   1   1   1   1
234   1   1   1   1   1   1   1   1   1   1   1   1
235   1   1   1   1   1   1   1   1   1   1   1   1
236   1   1   1   1   1   1   1   1   1   1   1   1


--------------------------------------------------------------
ATLAS_1JET_8TEV_R06:
999 200 201 202 203 204 205 206 207 233 234 235 236
200   1   1   1   1   1   1   1   1   1   1   1   1
201   1   1   1   1   1   1   1   1   1   1   1   1
202   1   1   1   1   1   1   1   1   1   1   1   1
203   1   1   1   1   1   1   1   1   1   1   1   1
204   1   1   1   1   1   1   1   1   1   1   1   1
205   1   1   1   1   1   1   1   1   1   1   1   1
206   1   1   1   1   1   1   1   1   1   1   1   1
207   1   1   1   1   1   1   1   1   1   1   1   1
233   1   1   1   1   1   1   1   1   1   1   1   1
234   1   1   1   1   1   1   1   1   1   1   1   1
235   1   1   1   1   1   1   1   1   1   1   1   1
236   1   1   1   1   1   1   1   1   1   1   1   1


--------------------------------------------------------------
CMS_2JET_7TEV:
999 200 201 202 203 204 205 206 207 233 234 235 236
200   1   1   1   1   1   1   1   1   1   1   1   1
201   1   1   1   1   1   1   1   1   1   1   1   1
202   1   1   1   1   1   1   1   1   1   1   1   1
203   1   1   1   1   1   1   1   1   1   1   1   1
204   1   1   1   1   1   1   1   1   1   1   1   1
205   1   1   1   1   1   1   1   1   1   1   1   1
206   1   1   1   1   1   1   1   1   1   1   1   1
207   1   1   1   1   1   1   1   1   1   1   1   1
233   1   1   1   1   1   1   1   1   1   1   1   1
234   1   1   1   1   1   1   1   1   1   1   1   1
235   1   1   1   1   1   1   1   1   1   1   1   1
236   1   1   1   1   1   1   1   1   1   1   1   1


--------------------------------------------------------------
CMS_1JET_8TEV:
999 200 201 202 203 204 205 206 207 233 234 235 236
200   1   1   1   1   1   1   1   1   1   1   1   1
201   1   1   1   1   1   1   1   1   1   1   1   1
202   1   1   1   1   1   1   1   1   1   1   1   1
203   1   1   1   1   1   1   1   1   1   1   1   1
204   1   1   1   1   1   1   1   1   1   1   1   1
205   1   1   1   1   1   1   1   1   1   1   1   1
206   1   1   1   1   1   1   1   1   1   1   1   1
207   1   1   1   1   1   1   1   1   1   1   1   1
233   1   1   1   1   1   1   1   1   1   1   1   1
234   1   1   1   1   1   1   1   1   1   1   1   1
235   1   1   1   1   1   1   1   1   1   1   1   1
236   1   1   1   1   1   1   1   1   1   1   1   1
```
Here are the values of the chi2s of the jet data sets:
- before the fix https://vp.nnpdf.science/Tl9w77h6TcOc9MfuROCDug==
- after the fix https://vp.nnpdf.science/qca2cuwrQaqHX4azqjTydg==

Everything seems good to me.

**Comment by enocera** [comment]
@RoyStegeman When/if you have time/band please check that everything is indeed fine.

**Comment by RoyStegeman** [comment]
Excellent! Thanks for this. I'll redownload the theories and do a quick check tomorrow.

I'm currently collecting some more samples (meaning replicas) for the chi2 distribution of the simultaneous fit to NNPDF3.1 data, once that is completed later this week I will try to start a fit to 4.0 data.

**Comment by RoyStegeman** [comment]
@enocera is it possible something went wrong while updating theory 236? It is not listed on the server: https://nnpdf.web.cern.ch/nnpdf/tables/

**Comment by enocera** [comment]
Oh Dear, let me check immediately!

**Comment by enocera** [comment]
It should be fixed now.

**Comment by RoyStegeman** [comment]
Excellent, thanks!
