### ISSUE TITLE
Add references to all PLOTTING files

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#1535]
We have some limited amount of and support for references in the plotting files. E.g.

```
PLOTTING_NTVNBDMNFe_dw_ite.yml
6:data_reference: Goncharov:2001qe,MasonPhD
```
where the ids are meant to correspond to ids from some bib file.
But those are only in a few places and unused at the moment. The `report` action of reportengine has the possibility of calling `pandoc` with a bibliography file, but that is also unused at the moment.  

Ideally the references would be required and used to generate tables, such as those in the paper with vp (ideally directly in LaTex format which is easy enogh with pandas). This would not only save time when writing papers but also facilitate answering what a dataset is, which is not so readily obvious from the available data (even if it can be worked out somewhat laboriously). While this is all supposed to be in the new commondata format, the required work is largely independent, as someone has to put the references in a machine readable place and write the vp actions anyway hooking up the bibliography.

**Comment by Zaharid** [comment]
@AleCandido I was hoping to see some of that info in the runcards repo, e.g. here
https://github.com/NNPDF/runcards/blob/master/nnpdf31_proc/NNPDF_WMZ_14TEV_40_PHENO/metadata.txt
but it isn't there. Am I looking in the wrong place?

**Comment by Zaharid** [comment]
@scarlehoff This looks like a small thing someone starting in Milan could benefit from. Maybe with some oversight from @enocera who has strong opinions on LaTeX table formatting.

**Comment by felixhekhorn** [comment]
> @AleCandido I was hoping to see some of that info in the runcards repo, e.g. here https://github.com/NNPDF/runcards/blob/master/nnpdf31_proc/NNPDF_WMZ_14TEV_40_PHENO/metadata.txt but it isn't there. Am I looking in the wrong place?

@Zaharid actual datasets (such as NuTEV in your example) contain references to the arxiv and hep-data (if available): e.g. https://github.com/NNPDF/runcards/blob/8293f70278ea4224948371cb0a3823688abb1fbd/nnpdf31_proc/NUTEV_CC_NB_FE_SIGMARED/metadata.txt

I think your example is a pheno study (correct @cschwan ?) with no paper associated

**Comment by cschwan** [comment]
@felixhekhorn correct. Now that the NNPDF4.0 paper has at least the arxiv ID we should add it to the metadata (and later on the DOI).

**Comment by Zaharid** [comment]
Right, thanks I am thinking we probably want to store the ugly bibtex ids somewhere as those are in the end needed to make tables. Unless there are other ideas?

**Comment by cschwan** [comment]
@Zaharid if you have the arxiv ID you can query that on inspirehep.net to convert it into bibtex code; it should even have an API for that, I think.

**Comment by AleCandido** [comment]
> @Zaharid if you have the arxiv ID you can query that on inspirehep.net to convert it into bibtex code; it should even have an API for that, I think.

Indeed, there is https://github.com/inspirehep/rest-api-doc#external-identifiers

**Comment by Zaharid** [comment]
As discussed, we would like to:

  - Refer to inspire as primary reference formats. Others are at best secondary.
  - Generate bibliography files on demand by calling the Inspire API (with the info on the meta/plotting files). That would be done in a production rule.
  - Use that to generate latex exported tables and other artifacts.

**Comment by scarlehoff** [comment]
Superseded by #1709
