### ISSUE TITLE
Tidy up closure test random generation

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#1536]
We are using some c++ era logic for setting up the random split in closure tests:

https://github.com/NNPDF/nnpdf/blob/53a145fc86c4f17abf0bf2960900cd6d8aeafe3c/validphys2/src/validphys/filters.py#L80

I imagine this was left to keep backwards compatibility so that old fits had coherent random generation. But we should say goodbye to it if we are going to remove the hard dependency on libnnpdf. On top of that, I can't say I follow (or remember) the logic there: The runcards require a `seed` parameter that is undocumentend, not used anywhere else, and that seems to be unused, as we are immediately reseeding with `fiterseed`.

**Comment by scarlehoff** [comment]
Fixed by #1660
