### ISSUE TITLE
The chi2 in the vp reports is not taking into account the thcovariance matrix

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/nnpdf#1554]
I'm not convinced we are using the theory covariance matrix to compute the chi2 in the reports. Everything below needs to be actually checked of course, but it would be consistent with what we see in the reports.

Having a thcovmat takes you here:

https://github.com/NNPDF/nnpdf/blob/1c86eb52897176240a3c6e627c032da7c296001d/validphys2/src/validphys/config.py#L1629

But when you follow that track and go to here https://github.com/NNPDF/nnpdf/blob/1c86eb52897176240a3c6e627c032da7c296001d/validphys2/src/validphys/results.py#L522

Which uses the covmat from the `results` but the results use `covariance matrix`

https://github.com/NNPDF/nnpdf/blob/1c86eb52897176240a3c6e627c032da7c296001d/validphys2/src/validphys/results.py#L456

which alas, doesn't take into acount the thcovmat

https://github.com/NNPDF/nnpdf/blob/1c86eb52897176240a3c6e627c032da7c296001d/validphys2/src/validphys/config.py#L721

(；⌣̀_⌣́)

**Comment by andreab1997** [comment]
Indeed, doing `vp-comparefits` on exactly the same fits (namely _220325-ab-nnpdf31like_wthcovmat_fullcovmat_ and _220325-ab-nnpdf31like_baseline_fullcovmat_) with and without the flag `--thcovmat_if_present` you get exactly the same result for the chi2. This of course confirms that something is wrong in `vp-comparefits`.

**Comment by Zaharid** [comment]
Can this be closed?

**Comment by scarlehoff** [comment]
Yes, I believe #1560 fixed this.
