### ISSUE TITLE
Different tr/vl split in multi-replicas fit

### ISSUE THREAD

**Issue by Radonirinaunimi** [NNPDF/nnpdf#1555]
Since #1529 fixes the memory bottleneck during a multi-replicas fit, it would be nice to investigate the possibility of doing such a fit with a different training and validation split per replicas. This will potentially allow us (in the future) to hyperoptimize at the level of the distribution (based on some figure of merits different from the `chi2`). (cc @goord)

**Comment by goord** [comment]
Hi @Radonirinaunimi and @scarlehoff I am working on this in following branch: https://github.com/LHC-NLeSC/nnpdf/tree/trvlsplit-par-replicas

**Comment by goord** [comment]
Hi @Radonirinaunimi and @scarlehoff a first version of the training-validation split per parallel replica is done. For the basic parallel runcard (10 replicas), the results are (to my knowledge) identical between a serial run and a parallel run. We haven't monitored the memory usage yet, the current implementation is straightforward in the sense that it injects the masked FK-tables into observablewrappers for each dataset x replica combination.

Some boilerplate code had to be written to collect the partial losses from the ndatasets x nreplicas output layers. I also haven't tested the serial workflow with the above branch, it may be broken.

Point of this exercise is to allow me to get a bit acquainted with the code and establish a baseline version which we can start to improve upon. I guess the next step will be to replace the output layers with mask layers connected to the same chunk of python memory...

**Comment by scarlehoff** [comment]
Hi @goord, could you open a PR? Just to it is easier to inspect the differences between the codes. I don't know how much the fitting code has changed since you branched out (hopefully not much!) but merging might be tricky.

**Comment by goord** [comment]
ok will do

**Comment by Radonirinaunimi** [comment]
Thanks @goord, maybe also for completeness, I am attaching here the results of the compare fits that you sent to me on the slack yesterday in case Juan is interested to see it (also I haven't been able to provide comments).

[comparefits-basic.tar.gz](https://github.com/NNPDF/nnpdf/files/9827380/comparefits-basic.tar.gz)

One thing that I'd like to see is the comparison in which the replicas seeds are different, since now it is a bit hard really do the comparisons given that everything is exactly the same and whether that is expected with the changes.

**Comment by scarlehoff** [comment]
Well, if the sequential run and the parallel run give 100% the same result, that would be perfect and exactly what we want.

If, in addition, it is exactly the same as previous runs, even better!

**Comment by Radonirinaunimi** [comment]
> Well, if the sequential run and the parallel run give 100% the same result, that would be perfect and exactly what we want.
> 
> If, in addition, it is exactly the same as previous runs, even better!

Indeed! But to rule out completely any cases in which some additional bugs have not been introduced, one needs to also check in which variations in randomization still yield consistent result.
> 
> I would like to see the report with the full NNPDF4.0 dataset, so that we know it works at least for all datasets we already have (the only corner case that comes to mind is 1-point datasets, but one never knows)

This would be a good test indeed, I don't know about the memory footprint with this (maybe @goord  has some idea), but I'd expect that one would only be able to run a few replicas and there (if everything works) we should see compatible results with the statistics not being exactly the same.

**Comment by scarlehoff** [comment]
> I don't know about the memory footprint with this (maybe @goord has some idea)

Just to make sure, for the sequential one should be unchanged right?

**Comment by goord** [comment]
yes.

So for the NNPDF4 test which runcard exactly and how many replicas shall I use? I can combine that test with a memory usage measurement

**Comment by scarlehoff** [comment]
This runcard here https://github.com/NNPDF/nnpdf/blob/master/n3fit/runcards/reproduce_nnpdf40/NNPDF40_nnlo_as_01180_1000.yml

The number of replicas doesn't matter (as long as it is the same number in the sequential/master test)
