### ISSUE TITLE
Document usage of regularised covariance matrix fits

### ISSUE THREAD

**Issue by J-M-Moore** [NNPDF/nnpdf#1558]
I am currently trying to run a fit with a regularised covariance matrix, but struggling to understand how to do so from the docs. It might be useful if they were updated. <https://docs.nnpdf.science/figuresofmerit/index.html#regularized-covariance-matrices>

**Comment by J-M-Moore** [comment]
It seems that using:

`norm_threshold: value`

works in the runcard, this should probably be mentioned in the documentation.

**Comment by J-M-Moore** [comment]
After running a fit with the setting `norm_threshold: 4` in the runcard, I've been trying to use `vp-comparefits`. However, there is no option in `vp-comparefits` to use the regularised covariance matrix, so we are getting incorrect chi^2 values out.

**Comment by RoyStegeman** [comment]
I wrote that part of the documentation without much (or any) knowledge about the technical aspects of some of the listed covmats. That page is mostly intended to highlight that what we call the loss function in nnpdf depends on context and that it's not just the standard chi2 that some people may expect. 

If you would like to extend the explanation in the documentation feel free to open a PR. That would be very much appreciated. 

> After running a fit with the setting `norm_threshold: 4` in the runcard, I've been trying to use `vp-comparefits`. However, there is no option in `vp-comparefits` to use the regularised covariance matrix, so we are getting incorrect chi^2 values out.

vp-comparefits is just a function that calls runs validphys with the runcard linked below. I'm not sure what you mean when you say that the option is not there, but if you mean that `vp-comparefits`  does not have a flag that allows you to use the covmat maybe you can add the `norm_threshold`  key to this runcard?

https://github.com/NNPDF/nnpdf/blob/1c86eb52897176240a3c6e627c032da7c296001d/validphys2/src/validphys/comparefittemplates/comparecard.yaml

**Comment by J-M-Moore** [comment]
Thanks Roy! I guess a new PR would be sensible for the documentation then.

> vp-comparefits is just a function that calls runs validphys with the runcard linked below. I'm not sure what you mean when you say that the option is not there, but if you mean that vp-comparefits does not have a flag that allows you to use the covmat maybe you can add the norm_threshold key to this runcard?

Yes, that's what I ended up doing. I'm not sure what should be done though, given that the fit used a regularised covariance matrix - clearly vp-comparefits doesn't know this, and hence computes incorrect values of the chi2 unless you go to the runcard it draws from.

**Comment by RoyStegeman** [comment]
That's a good point, I suppose one could indeed add a flag that sets the `norm_threshold` key, similar to how there is a `--use_thcovmat_if_present` to use the theory covariance matrix to calculate the statistical estimators when producing the report. Perhaps the default behavior should be that it takes the corresponding value from the fit.

**Comment by Zaharid** [comment]
Maybe something like that. Indeed it seems the most sensible default is to do the same thing as the fit does. While other things could be interesting (either looking at the regularized chi2 without refitting or look at the "real" chi2 of a regularized fit) I am undecided if we should provide all the command line options under the sun.

The situation is not dissimilar for weighted fits (where we hard code displaying the unweighted chi2) and theory covmats, where we have too many options.

I suppose one may think of some supplementary runcard with precise covmat control options, but then again there is hacking the comparefit app which can also do that job...

**Comment by Zaharid** [comment]
Anyway I am going to declare that this issue is about the docs in order to make some progress. If there is interest in improving comparefits, please open another issue and/or pr.
