### ISSUE TITLE
NNPDF in master failing - A problem with the server?

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/nnpdf#1579]
As per title, it seems the `conda install nnpdf --yes` step in the github workflow fails (some unresolved dependencies).

The tests themselves work (which means conda is able to install the package after building it) and apparently the package was uploaded to the server. However the packages are not there (at least [not publicly accessible?](https://packages.nnpdf.science/conda/linux-64/) -none of the recent ones are- and I don't have access to (that part of) the server to actually check or fix it.

Since there was the problem with the server a few months ago, #1523, I wonder whether the restored server is simply not indexing conda packages at all?

**Comment by Zaharid** [comment]
Uh. I get an error running conda index

```
(base) [nnpdf@nnpdf public]$ conda index .
concurrent.futures.process._RemoteTraceback:                                    
'''                                                                             
Traceback (most recent call last):                        | 0/2 [00:00<?, ?it/s]
  File "/home/nnpdf/miniconda3/lib/python3.7/concurrent/futures/process.py", line 360, in _queue_management_worker
    result_item = result_reader.recv()
  File "/home/nnpdf/miniconda3/lib/python3.7/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 1 required positional argument: 'msg'
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nnpdf/miniconda3/bin/conda-index", line 11, in <module>
    sys.exit(main())
  File "/home/nnpdf/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_index.py", line 91, in main
    return execute(sys.argv[1:])
  File "/home/nnpdf/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_index.py", line 87, in execute
    current_index_versions=args.current_index_versions_file)
  File "/home/nnpdf/miniconda3/lib/python3.7/site-packages/conda_build/api.py", line 401, in update_index
    subdirs=ensure_list(subdir), current_index_versions=current_index_versions)
  File "/home/nnpdf/miniconda3/lib/python3.7/site-packages/conda_build/index.py", line 293, in update_index
    current_index_versions=current_index_versions)
  File "/home/nnpdf/miniconda3/lib/python3.7/site-packages/conda_build/index.py", line 804, in index
    subdir, verbose=verbose, progress=progress)
  File "/home/nnpdf/miniconda3/lib/python3.7/site-packages/conda_build/index.py", line 943, in index_subdir
    fn, mtime, size, index_json = future.result()
  File "/home/nnpdf/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/nnpdf/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

I am going to guess python 3.7 is too old and we should update that in the server. Not volunteering.

PS: Update the channels to

```
  - https://packages.nnpdf.science/private
  - https://packages.nnpdf.science/public
```

(we had to change it because of some conda bug).

**Comment by Zaharid** [comment]
...also https://bugs.python.org/issue37208 just to make sure you can't tell what is going on.

**Comment by scarlehoff** [comment]
Did we update something in the server such that 3.7 doesn't work any longer?

If only we had #1531 ... or got rid of C++ to make the transition to pip easier #1578 ...

**Comment by Zaharid** [comment]
I updated the relevant package and seems to run now with the following output

```
(base) [nnpdf@nnpdf public]$ conda index .
Subdir: linux-64:   0%|                                                                         | 0/3 [00:00<?, ?it/sWARNING:/home/nnpdf/miniconda3/lib/python3.7/site-packages/conda_package_handling/tarball.py:Failed extraction with libarchive... falling back to python implementation                                                | 0/2 [00:00<?, ?it/s]
WARNING:/home/nnpdf/miniconda3/lib/python3.7/site-packages/conda_package_handling/tarball.py:Failed extraction with libarchive... falling back to python implementation
Package /home/nnpdf/packages/conda/linux-64/nnpdf-4.0.4.176+g3a249440a-py39h9a426be_0.tar.bz2 appears to be corrupt.  Please remove it and re-download it
ERROR:conda_build.index:Package /home/nnpdf/packages/conda/linux-64/nnpdf-4.0.4.176+g3a249440a-py39h9a426be_0.tar.bz2 appears to be corrupt.  Please remove it and re-download it
Compressed file ended before the end-of-stream marker was reached
ERROR:conda_build.index:Compressed file ended before the end-of-stream marker was reached
```

I suppose the bad files were giving it trouble before.

I also had to fix the fact that condas own `conda-package-handling` package had an undeclared dependency on `python-libarchive-c`, which moves me closer to agreeing using something else might be good eventually.

**Comment by scarlehoff** [comment]
And does it work once the corrupted package is removed?

**Comment by scarlehoff** [comment]
I don't know, wanted to ask before resending the workflow. Let's see.

**Comment by scarlehoff** [comment]
The error has changed https://github.com/NNPDF/nnpdf/runs/7284109391?check_suite_focus=true#step:9:1195

**Comment by Zaharid** [comment]
for one I don't think the automated indexing is working so I had to run it manually. After then it installed v100. v99 seems corrupted somehow.

**Comment by scarlehoff** [comment]
Ok, I just found out that we have two scripts to index the packages:

`index-public-pkgs.sh` and `index-packages-public.sh`. Turns out the one `crontab` tries to run is pointing to the wrong directory and the other is from 2020. I've left the one from 2020 running just in case it works.
