### ISSUE TITLE
Missing filter rules?

### ISSUE THREAD

**Issue by J-M-Moore** [NNPDF/nnpdf#1600]
The data for `ATLAS_TOPDIFF_DILEPT_8TEV_TTMNORM` is taken from Table 4 of https://www.hepdata.net/record/ins1477814. There are 6 points in the commondata file, and there are also 6 points in the HEPdata record, which is consistent. Since this is a normalised distribution, we need a filter rule in filters.yaml to cut one point, but I cannot find a filter rule. 

Similarly, the data for `CMS_TTBAR_2D_DIFF_MTT_TTRAP_NORM` is taken from Table 11 of https://www.hepdata.net/record/ins1516191. There are 16 points in the commondata file, and there are 16 points in the HEPdata record, which is consistent. Again, we need a filter rule in filters.yaml, but none is present.

Is my reasoning correct above? Can we add the missing filter rules?

**Comment by enocera** [comment]
@J-M-Moore My recollection is that we need a filter rule for the ATLAS distribution (the reason why there's not one is that we never use that distribution in NNPDF4.0), while we do NOT need one for the CMS 2D distribution. Let me check. Let's say that I'll do the check, together with #1576, over the week-end.

**Comment by J-M-Moore** [comment]
Thanks Emanuele, much appreciated! If the set isn't used in NNPDF4.0, but it still needs a filter rule, should we add it to filters.yaml or not?

**Comment by enocera** [comment]
Yes, we should.

**Comment by enocera** [comment]
This is fixed by #1602 . Theory 200 has been updated accordingly (I guess that this is the theory you use @J-M-Moore ).

**Comment by enocera** [comment]
@J-M-Moore I've added a filter rule for `ATLAS_TOPDIFF_DILEPT_8TEV_TTMNORM` and `ATLAS_TOPDIFF_DILEPT_8TEV_TTRAPNORM` in #1602. This is not completely clear to me that this is needed, given that, if the last bin were really linearly dependent from the others, the covariance matrix provided on Hepdata shoudl hav e azero eigenvalue. Which does not seem to be the exactly the case. Concerning `CMS_TTBAR_2D_DIFF_MTT_TTRAP_NORM`, we do not have absolute distributions, therefore I cannot tell whether the last bin is linearly dependent from the others or not. In the corresponding CMS paper, they include all the bins in a fit, therefore I conclude that we do not need a filter rule in this case.

**Comment by J-M-Moore** [comment]
Okay, thanks for looking into this so carefully Emanuele, it's very useful! I think this all sounds very reasonable; the filter rules you have added look good to me.

**Comment by enocera** [comment]
Closed via #1602
