### ISSUE TITLE
Extra parameters in closure test runcards

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#1623]
The closure tests depend on the prepare_nnpdf_rng function here 
https://github.com/NNPDF/nnpdf/blob/94b80c35618bd55ae463b5806bf2b5886f6ecad6/validphys2/src/validphys/filters.py#L80

which uses the c++ rng. As far as I remember this was kept so that we could use older closure tests while analyzing other parts of the code. This doen't make a lot of sense any longer. Not only are we keeping a dependency on the old code, risking having the same problem when people produce new batches of closure tests, but we end up with required keys that are not documented, e.g. here

https://docs.nnpdf.science/tutorials/closuretest.html

We should get rid of that function and use the same rng as for nfit.

**Comment by comane** [comment]
@Zaharid, I think this issue can be closed since in the new python closure test branch the function
`prepare_nnpdf_rng(filterseed:int, rngalgo:int, seed:int): ` has been removed
