### ISSUE TITLE
Add a basis with c & cbar

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/nnpdf#1627]
Which also requires ensuring that the rotation to the fktable basis and sum rules work.

- [x] Add the c-cbar basis
- [x] FKTable rotation (see https://github.com/NNPDF/nnpdf/issues/1627#issuecomment-1311600732)
- [x] Sum rules 
- [x] Check that old FK Tables are not optimizing out the ccbar asymmetry 
- [ ] Check that pineappl FK Tables are not optimizing out the ccbar asymmetry 

@felixhekhorn I added you to this issue just because of the last point ofc, let us now and if it is we just do a theory 4XY with the asymmetry.

Although I wonder whether the fktables in theory 200 would allow for it (I'll have a look at that)

**Comment by tgiani** [comment]
thank you @scarlehoff I m happy to work on this

**Comment by tgiani** [comment]
in the FK tables I think there is already V15, which now is taken equal to V, no?

**Comment by felixhekhorn** [comment]
> * Check that old FK Tables are not optimizing out the ccbar asymmetry

- the relevant line in pineko is: https://github.com/NNPDF/pineko/blob/f7164fa8df0bf78a2cde71dd30fede24779d4e47/src/pineko/evolve.py#L182
- which calls this pineappl function https://github.com/NNPDF/pineappl/blob/58158e6d97f8e6a8a5b52d27743dd7b9b1924a06/pineappl/src/fk_table.rs#L291
- however, the problem is that the argument of that function is currently constructed by investigating various fields in the runcard https://github.com/NNPDF/pineko/blob/f7164fa8df0bf78a2cde71dd30fede24779d4e47/src/pineko/theory_card.py#L46 which makes it impossible at the moment to generate `Nf4Ind` which is the setting we need. We need to adjust that function.

**Comment by scarlehoff** [comment]
> in the FK tables I think there is already V15, which now is taken equal to V, no?

Yes. The value does exist. I'm wondering whether in Th 200 they are optimized by making V = V + V15.

**Comment by tgiani** [comment]
from the ```n3fit``` point of view, in order to add a parameterization for c-cbar, is it enough to use ```nodes_per_layer: [25, 20, 9]``` in the runcard and then just change the FK table rotation to account for V15?

**Comment by scarlehoff** [comment]
Yes! It is just like in the perturbative case.

But we the basis needs to be known by validphys, otherwise it won't be able to do the rotation.

Sumrules, integrability, etc is performed (iirc) always in the 14-flavours basis so it should be fine.

**Comment by scarlehoff** [comment]
I've removed my previous msg. No, unfortunately in `pdfbases.py` we implicitly assume that the maximum number of flavours that are going to be fitted is 8.

So we need to scratch this function: 
https://github.com/NNPDF/nnpdf/blob/94b80c35618bd55ae463b5806bf2b5886f6ecad6/validphys2/src/validphys/pdfbases.py#L656

And then address this TODO from 3 years ago https://github.com/NNPDF/nnpdf/blob/94b80c35618bd55ae463b5806bf2b5886f6ecad6/n3fit/src/n3fit/layers/rotations.py#L64 which didn't matter until now.

**Comment by Radonirinaunimi** [comment]
> And then address this TODO from 3 years ago
> 
> https://github.com/NNPDF/nnpdf/blob/94b80c35618bd55ae463b5806bf2b5886f6ecad6/n3fit/src/n3fit/layers/rotations.py#L64
> which didn't matter until now.

Oh, if you remember @scarlehoff we discussed about this a bit at some point in the context of nuclear PDFs (where only 6 flavours are active) and I sort of recall I had a go on this.

**Comment by tgiani** [comment]
right yes I remember this function. But it s ok, just need to change it with the new basis definition before doing the rotation to the FK basis I would say

**Comment by scarlehoff** [comment]
Yes. It shouldn't be a problem. It's just not as ready as I thought :P

> Oh, if you remember @scarlehoff we discussed about this a bit at some point in the context of nuclear PDFs (where only 6 flavours are active) and I sort of recall I had a go on this.

Right. But in principle this is the opposite scenario. Actually in this case the "relevant" part is in the vp side so the two changes should not be incompatible I'd say.

**Comment by tgiani** [comment]
I ll have a go and open a PR to iterate with you and @Radonirinaunimi

**Comment by scarlehoff** [comment]
In the meantime, I had a look at theory 200 and there is V15  in the fktables so we can use th 200 for now.

**Comment by scarlehoff** [comment]
Closed with #1629 

For the fktables with ccbar, that's pineko's job https://github.com/NNPDF/pineko/issues/64
