### ISSUE TITLE
One point datasets always end up in validation split

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#1634]
When the dataset has one data point and a `frac` < 1 the code here

https://github.com/NNPDF/nnpdf/blob/43e7e752f04852bd9f2b458e6d03fb088586e762/validphys2/src/validphys/n3fit_data.py#L95

rounds the number of training points to zero, and so the dataset end in validation for all replicas. This may cause some total cross sections like  ATLASTTBARTOT7TEV  to end up with a somewhat worse chi2.

**Comment by scarlehoff** [comment]
I guess when `ndata` = 1 we should do `trmax = (np.random.rand > frac)` instead.

**Comment by Zaharid** [comment]
Should ideally also have a full fit before and after. It was on my todo list but...
