### ISSUE TITLE
Buildmaster Installation issue

### ISSUE THREAD

**Issue by t7phy** [NNPDF/nnpdf#1635]
While compiling the buildmaster, it runs into an error as follows (tried on 2 different PCs):

(nnpdf-dev) tanishq@ts:~/nnpdfgit/nnpdf/buildmaster/build$ make -j && make install
Consolidate compiler generated dependencies of target buildmaster
[  1%] Linking CXX executable buildmaster
/home/tanishq/miniconda3/envs/nnpdf-dev/bin/../lib/gcc/x86_64-conda-linux-gnu/11.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lasan: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/buildmaster.dir/build.make:1761: buildmaster] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/buildmaster.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by Zaharid** [comment]
Could you post

```
$ conda list gxx_linux-64
```

**Comment by t7phy** [comment]
`(nnpdf-dev) tanishq@ts:~/nnpdfgit/nnpdf/buildmaster/build$ conda list gxx_linux-64
# packages in environment at /home/tanishq/miniconda3/envs/nnpdf-dev:
#
# Name                    Version                   Build  Channel
gxx_linux-64              11.2.0               hc2dff05_0  
`

**Comment by t7phy** [comment]
(nnpdf-dev) tanishq@ts:~/nnpdfgit/nnpdf/buildmaster/build$ conda list gxx_linux-64
# packages in environment at /home/tanishq/miniconda3/envs/nnpdf-dev:
#
# Name                    Version                   Build  Channel
gxx_linux-64              11.2.0               hc2dff05_0

**Comment by t7phy** [comment]
```
(nnpdf-dev) tanishq@ts:~/nnpdfgit/nnpdf/buildmaster/build$ conda list gxx_linux-64
# packages in environment at /home/tanishq/miniconda3/envs/nnpdf-dev:
#
# Name                    Version                   Build  Channel
gxx_linux-64              11.2.0               hc2dff05_0  
```

**Comment by Zaharid** [comment]
I cannot reproduce this. Are the rest of the build installations working?

**Comment by t7phy** [comment]
I firstly followed the https://docs.nnpdf.science/get-started/installation.html#installation-from-source, everything went fine during this step but then while following https://docs.nnpdf.science/buildmaster.html, I get the above stated error.

**Comment by Zaharid** [comment]
Do you have the file

```
/home/tanishq/miniconda3/envs/nnpdf-dev/lib/lib/libasan.so.6
```

**Comment by t7phy** [comment]
No its not there

**Comment by Zaharid** [comment]
Looks like a bug in conda. I can reproduce it. 

using the alternative mamba program worked for me

```
 mamba install nnpdf --only-deps 
```

**Comment by t7phy** [comment]
That worked. Thanks :)
