### ISSUE TITLE
vp-comparefits blows up memory

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#1637]
If I run  comparefits like

```
vp-comparefits NNPDF40_nnlo_as_01180_corr_s2 NNPDF40_nnlo_as_01180_corr_s2 --title="test" --author="Zahari Kassabov" --keywords="test" --debug
```

with a fully updated conda environment I see that the memory usage blows up to over 32 Gb, causing it to swap and never finish. I think that is because of the inclusion of the overfitting metric. This causes a lot of overhead by things like

```
[DEBUG]: Found sep_mult for spec (('dataspecs', 0), ('t0_info', 0), ('t0_info', 0), ('pdfreplicas', 25), 'fitenvironment', ('group_dataset_inputs_by_experiment', 0)) at 6
```

which involves blowing many things over replicas.

Collecting over replicas is not a very good idea.

**Comment by Zaharid** [comment]
See #1503.

**Comment by scarlehoff** [comment]
Let's take it out from comparefits for the time being.

We've also found a few problems and, more importantly, as soon as #1636 is merged we lose (again) the possibility of reusing all fits.

That said, I don't think I've seen this? (I've been definitely being using the latest overfit metric but not the latest conda, I've been updating just vp)

**Comment by Zaharid** [comment]
Agree that its best to take it out ASAP. I haven't exactly found what is blowing in memory, but pretty sure it is this (among other things because it worked fine with earlier versions).

**Comment by RoyStegeman** [comment]
I generate all comparefit reports on the cluster for a reason. The overfit metric is expensive to evaluate and we can reduce the memory usage a bit, but I think we should accept that the comparefit report is just not something that necessarily has to be possible to generate on a laptop. 

We could consider addressing #1553 and exclude (among other things) the overfit metric.

**Comment by scarlehoff** [comment]
> We could consider addressing https://github.com/NNPDF/nnpdf/issues/1553 and exclude (among other things) the overfit metric.

Yes, this would be great. But I would like to be able to run comparefit in my desktop computer and 32GB would be too much (another reason not to use conda I guess :P)

**Comment by Zaharid** [comment]
I think the pdfs I am trying have way more than 100 replicas. Nothing to do with conda.

**Comment by scarlehoff** [comment]
Ah, ok, that might be it then.

**Comment by RoyStegeman** [comment]
No the overfit metric currently just uses all other replicas that have been generated as part of the fit to evaluate the R_O. So kind of only works for a fit with O(10) replicas. I suppose we may as well generate a number of pseudodatasets on the fly where the number can be set in the runcard.

**Comment by RoyStegeman** [comment]
> We've also found a few problems and, more importantly, as soon as https://github.com/NNPDF/nnpdf/pull/1636 is merged we lose (again) the possibility of reusing all fits.

This is not correct, I think? If the masks are stored correctly we can still evaluate the R_O from fits done before this change.

**Comment by scarlehoff** [comment]
But if they are not stored they cannot be regenerated. 

Also, I meant `old` instead of `all` :__

**Comment by RoyStegeman** [comment]
Ah right, I'm actually not sure if we regenerate or load them. If we load it should be fine
