### ISSUE TITLE
There is something strange with E906

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/nnpdf#1639]
I'm having troubles creating new fktables for E906 and testing against theory 200 I've noticed something very strange: the results are very dependent of the PDF being used in theory 200. In particular, if one uses a different PDF the results change by quite a lot. With even a negative value in the last bin!

Below there's a 31 vs 40 comparison:

```python
from validphys.api import API
import pandas as pd
from validphys.convolution import central_predictions
pdf_40 = API.pdf(pdf="NNPDF40_nnlo_as_01180")
pdf_31 = API.pdf(pdf="NNPDF31_nnlo_as_0118")
ds_200 = API.dataset(dataset_input={"dataset": "DYE906R_dw_ite", "cfac": ["ACC"]}, theoryid=200, use_cuts = "internal")
res_40 = central_predictions(ds_200, pdf_40)
res_31 = central_predictions(ds_200, pdf_31)
pd.concat([res_40, res_31], axis=1)
```

```
             0         0
data
0     1.151581  3.042647
1     1.172257  2.044257
2     1.162259  1.886642
3     1.121157  1.948976
4     1.054628  3.421160
5     1.009504 -0.492614
```

What makes this more strange is that if I try with theory 400, which was constructed to be the same as theory 200, we get good agreement with NNPDF40 (for everything but the last bin, but we knew that) but the results are very different for NNPDF31.

```python
from validphys.api import API
import pandas as pd
from validphys.convolution import central_predictions
pdf_40 = API.pdf(pdf="NNPDF40_nnlo_as_01180")
pdf_31 = API.pdf(pdf="NNPDF31_nnlo_as_0118")
ds_400 = API.dataset(dataset_input={"dataset": "DYE906R_dw_ite", "cfac": ["ACC"]}, theoryid=400, use_cuts = "internal")
res_40 = central_predictions(ds_400, pdf_40)
res_31 = central_predictions(ds_400, pdf_31)
pd.concat([res_40, res_31], axis=1)
```

```
             0         0
data
0     1.157491  2.628375
1     1.181081  1.793940
2     1.174450  1.581144
3     1.137315  1.449514
4     1.073738  1.366556
5     1.032809  1.543372
```

I'm not sure what to make of this. My guess is that the difference between NNPDF40 and NNPDF31 is the fact that NNPDF31 can have some small negativity but the changes seem way too big (and, more importantly, if we had done the checks with 3.1 instead of 4.0 we would've noticed something was wrong).

Note that, when using good-positive PDFs, we can fit the dataset and we get a very good chi2 https://vp.nnpdf.science/07wMgql6RTCOcYqrWJlDJw==/matched_datasets_from_dataspecs44_dataset_report_report.html

For context: the reason I was trying NNPDF3.1 is because I'm comparing the NNLO k-factors with the NNLO fk-tables and I was getting agreement for all tables but this one... which suddenly was completely wrong!

I'm opening the issue in this repo because the issue (or feature) affects also theory 200.

**Comment by Zaharid** [comment]
Just to note that when we tried to reproduce the 3.1 fit 210705-nnfit-meth-001from https://www.wiki.ed.ac.uk/display/nnpdfwiki/NNPDF4.0+final+fits which includes

```
  - {dataset: DYE906R, frac: 1.0, cfac: [ACC,QCD]}
```

the chi2 of that dataset was terrible, unlike in the original fit.  The results with that fktable (and with the acc cfactor) critically depend on the pdf as well.

Not sure what that was about.

**Comment by enocera** [comment]
@Zaharid Just to confirm that I also observed the same. The thing that I don't understand is why the chi2 210705-nnfit-meth-001 was OK in the first place an why we cannot reproduce it.

**Comment by scarlehoff** [comment]
It's now worse, but it was already going in the wrong direction https://vp.nnpdf.science/lpsrN1PbSIOifWsA4eLv9A==/matched_datasets_from_dataspecs68_dataset_report_report.html

I wonder whether the chi2 is due to the change of prediction of the central value of the PDF to central value of the predictions. These two were supposed to be very close (and they are) most of the time but of course, this might not be the case if there are replicas that are so bad that are breaking the approximation...

**Comment by enocera** [comment]
@scarlehoff Which values do you get if you use 210705-nnfit-meth-002 (which is NNPDF3.1 methodology+ 4.0 positivity on the 4.0 data set)?

**Comment by scarlehoff** [comment]
```
from validphys.api import API
import pandas as pd
from validphys.convolution import central_predictions
pdf_40 = API.pdf(pdf="NNPDF40_nnlo_as_01180")
pdf_31 = API.pdf(pdf="210705-nnfit-meth-002")
ds_200 = API.dataset(dataset_input={"dataset": "DYE906R_dw_ite", "cfac": ["ACC"]}, theoryid=200, use_cuts = "internal")
res_40 = central_predictions(ds_200, pdf_40)
res_31 = central_predictions(ds_200, pdf_31)
pd.concat([res_40, res_31], axis=1)
```

```
             0         0
data
0     1.151581  1.107257
1     1.172257  1.128339
2     1.162259  1.108373
3     1.121157  1.060062
4     1.054628  0.974696
5     1.009504  0.845388
```

So yes, blaming it on the negative points seems to hold some water.

**Comment by enocera** [comment]
So, based on this, cannot we conclude that:
- The dependence of the DYE906 Xsec on the PDF set is after all not so surprising: the observable is sensitive to antiquarks at large x, which are typically very close to zero. Hence if one uses a PDF set in which there's no positivity small fluctuations of the PDF (which can go negative) translate in large differences of the observable (which, btw is a ratio).
- It remains unclear why we are not able to reproduce 210705-nnfit-meth-001 and also why the numbers pasted above are not the same as [here]( https://vp.nnpdf.science/xfx0HY10QhqZEY6rlBvANA==/matched_datasets_from_dataspecs68_dataset_report_report.html) for the 4th, 5th and 6th points.

**Comment by scarlehoff** [comment]
> The dependence of the DYE906 Xsec on the PDF set is after all not so surprising: the observable is sensitive to antiquarks at large x, which are typically very close to zero. Hence if one uses a PDF set in which there's no positivity, small fluctuations of the PDF (which can go negative) translate in large differences of the observable (which, btw is a ratio).

But then with theory 400 we should see the same thing. It seems the one in theory 400 remains positive even with NNPDF3.1. Which confuses me very much (because of the agreement with theory 200)

> It remains unclear why we are not able to reproduce 210705-nnfit-meth-001 and also why the numbers pasted above are not the same as [here](https://vp.nnpdf.science/xfx0HY10QhqZEY6rlBvANA==/matched_datasets_from_dataspecs68_dataset_report_report.html) for the 4th, 5th and 6th points.

I believe the reason for this could be the change from central value of the PDF to central value of the predictions. When we did this change we justified it saying that the changes were below the % which was acceptable. But maybe in cases like this (we probably checked with NNPDF40) these changes are much bigger!

**Comment by enocera** [comment]
> > The dependence of the DYE906 Xsec on the PDF set is after all not so surprising: the observable is sensitive to antiquarks at large x, which are typically very close to zero. Hence if one uses a PDF set in which there's no positivity, small fluctuations of the PDF (which can go negative) translate in large differences of the observable (which, btw is a ratio).
> 
> But then with theory 400 we should see the same thing. It seems the one in theory 400 remains positive even with NNPDF3.1. Which confuses me very much (because of the agreement with theory 200)

Ah, I hadn't got this part of the problem.

> 
> > It remains unclear why we are not able to reproduce 210705-nnfit-meth-001 and also why the numbers pasted above are not the same as [here](https://vp.nnpdf.science/xfx0HY10QhqZEY6rlBvANA==/matched_datasets_from_dataspecs68_dataset_report_report.html) for the 4th, 5th and 6th points.
> 
> I believe the reason for this could be the change from central value of the PDF to central value of the predictions. When we did this change we justified it saying that the changes were below the % which was acceptable. But maybe in cases like this (we probably checked with NNPDF40) these changes are much bigger!

I understand. I think I share your belief.

**Comment by scarlehoff** [comment]
Ok, no. My idea of the Stats thing was completely wrong. The results have not changed all the way since tag 4.0.3 which is the NNPDF4.0 fits tag

```
             0         0
data                    
0     1.151581  3.042648
1     1.172257  2.044257
2     1.162259  1.886643
3     1.121157  1.948977
4     1.054628  3.421161
5     1.009504 -0.49261
```
```
>>> validphys.__version__
'4.0.3.0+g1229126c3'
```

The only possibility is that the fktable changed? Or that I am looking at the wrong thing whatever that means.

**Comment by scarlehoff** [comment]
I'm trying to debug E906 and I'm finding the results to be unstable even in a grid-by-grid basis.
The E906 observable is a combination of 20 different fktables, all of which suffer of some degree of instability. Could it be just an unreliable observable?

Maybe the correct solution is to take it out of the fit, at least of fits that can go negative to some degree.

**Comment by scarlehoff** [comment]
With the latest update of E906 https://github.com/NNPDF/runcards/pull/164 (which add some fixes for bugs in vrap) we find the grids from vrap for Theory 400 to be exactly compatible with Theory 200.

Discussing with @cschwan, our conclusion was that the grids are unstable when the PDF go negative. Since we are composing 20 different grids, we are just seeing these instabilities explode.

I'm a bit worried about the NNLO c-factors in theory 200 that were used for NNPDF4.1 since they were computed with NNPDF31 and vrap (which is also unstable). On the other hand they are small and are only 6 points so probably not a big effect.

**Comment by enocera** [comment]
@scarlehoff @cschwan Thanks for the extensive checks. My impression is that while individual grids can be numerical unstable, once these are combined into a ratio (i.e. the measured observable) many of these instabilitites (which, in my opinion, are consistent across grids) cancel out. And likewise for K-factors, which are very close to one.

**Comment by Zaharid** [comment]
Do we understand things like being unable to reproduce the fit?

**Comment by scarlehoff** [comment]
With `210705-nnfit-meth-001` we have very unstable results as well

```
          0         0         1
0 -1.148496 -1.727128  0.664974
1  2.717509  2.528897  1.074583
2  2.501614  2.418208  1.034491
3 -3.782079 -3.999130  0.945726
4  0.460363  0.468808  0.981987
5  0.580766  0.594714  0.976546
```

for completeness, E906 with the reference PDF of the "unreproducible one" report:
```
0  1.172822  1.173934  0.999053
1  1.184242  1.184627  0.999675
2  1.168316  1.168210  1.000091
3  1.123454  1.123342  1.000099
4  1.054001  1.053653  1.000330
5  0.961515  0.961552  0.999961
```
