### ISSUE TITLE
Clarify pseudodata rebuilding workflow 

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#1641]
We have a number of tools relying on having explicit pseudodata for the fitted replicas (both the fluctuation and the training validation split, and then also implicitly the cuts). We have a way of storing all that which is not used often by default. 

And we have a way of “rebuilding” the data relying on things like the algorithms for splitting being unmodified and random streams being stable.

We have a tendency to break the later one which also adds constraints on how to modify things. I believe we should discuss what to do with it. As it is, I consider any modifications that change the pseudodata a breaking change requiring a version bumps (but covered by the compatibility policy which explicitly allows for randomly state changes). But perhaps we should simply deprecate that and mandate that pseudodata needs to be stored if we intend to use it later.

**Comment by Zaharid** [comment]
Cc @J-M-Moore

**Comment by scarlehoff** [comment]
> and then also implicitly the cuts

Yet another thing that has changed recently for several datasets.

---

Storing the pseudodata by default -instead of not doing it- would be the best thing we can do. One never knows when it will be neded.
One question, is it possible to make `reportengine` / `validphys` dump the pseudodata only after the fit is finished? 

(also, maybe we should dump it as one file to reduce cluttering filesystems)

**Comment by Zaharid** [comment]
You can make a provider depending on the fit for example. Or use the feature where you specify post actions like the figures do.

**Comment by scarlehoff** [comment]
I guess that's an answer for the last point?

For the rest, I'm happy with saving by default for now.

**Comment by Zaharid** [comment]
To me the core issue at hand is what to do with the existing rebuilding functionality. Do we delete it, document is as very unreliable, commit to making it reliable, something else?

**Comment by scarlehoff** [comment]
Documenting it as reliable seems the right thing to me.
A warning of "Rebuilding is only fully reliable when used with the exact commit the fit was made with" or something like that.
