### ISSUE TITLE
EMC F2C new pipeline

### ISSUE THREAD

**Issue by tgiani** [NNPDF/nnpdf#1652]
Is there a new pipeline theory where the data for EMC F2C are implemented? In th 400 this dataset is not there

**Comment by scarlehoff** [comment]
In theory 400 for now we have only implemented the datasets that were in the standard NNPDF40 runcard. To add new ones we have to add the corresponding runcards (and update the theory accordingly).

https://github.com/NNPDF/runcards

**Comment by enocera** [comment]
This is addressed by https://github.com/NNPDF/pinecards/pull/170 and https://github.com/NNPDF/theories/pull/3. The EMC F2c FK table is now available in theory 400.
