### ISSUE TITLE
Plot normalization with negative central values is wrong

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#1664]
We normalize errors by doing something like

```
normalized_error = original_error/central_value
```

when `central_value` is negative, this would result in error bars being negative. Previous versions of matplotlib would swallow this and set the error bar to zero, but recent ones complain with

```
ValueError: 'yerr' must not contain negative values
```

This could happen when one is computing a data theory comparison with an assymetry, or apparently with arclength plots (see #1657).

I believe the fix in the first case is making sure we use the absolute values.

Related #1657.

**Comment by J-M-Moore** [comment]
Fixed by https://github.com/NNPDF/nnpdf/pull/1665
