### ISSUE TITLE
Simplify development environment installation instructions

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#1690]
As of #1680 we have little need for the instructions here

https://docs.nnpdf.science/get-started/installation.html#installation-from-source

AFAICT it would only be needed for running buildmaster and hacking some old evolution tools.

A simpler procedure for Python only development would go along the lines of install package, and  `pip install -e .` on vp and n3fit. I think the current instructions could be stashed somewhere and have those simpler ones for a default dev environment.

**Comment by Zaharid** [comment]
@RoyStegeman  would you have a look here, given that it might help you for something else?

**Comment by RoyStegeman** [comment]
In principle being able to do `pip install` would make life easier,  though we still need lhapdf so if we don't use conda we'll need to add instructions for the intallation of lhapdf. I'm not sure what would be best as a recommended installation. Maybe you or @scarlehoff have thoughts on this?

**Comment by scarlehoff** [comment]
Yes. The pip-only install has two problems:

1. lhapdf
2. Putting the database and the profile file in the right places.

I haven't look at how to automatise in a reasonable manner 2. because of 1.

**Comment by Zaharid** [comment]
This issue is **not** about not using conda. It is about not installing C++ build dependencies for the dev environment.

**Comment by RoyStegeman** [comment]
> Putting the database and the profile file in the right places.

Yes this would have to be addressed first but that has to be done at some point anyway.
