### ISSUE TITLE
Bug in nnpdf/buildmaster/filters/ATLAS_2JET_7TEV_R06.cc

### ISSUE THREAD

**Issue by comane** [NNPDF/nnpdf#1700]
@enocera, There is a bug in line 201 of buildmaster/filters/ATLAS_2JET_7TEV_R06.cc

`fSys[i][133].mult = sys1;` should be replaced with `fSys[i][133].mult = sys;`

This has an impact on the covariance matrix.

**Comment by enocera** [comment]
@comane Thanks. Let me check.

**Comment by scarlehoff** [comment]
Buildmaster is no more
