### ISSUE TITLE
Change theory database from .db to .yaml

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/nnpdf#1705]
We have many people working on the database at the same time, which is creating constant problems because it is a binary file... maybe we should move all the information to a `.yaml` file with `id: information`? I don't think we lose much.

**Comment by enocera** [comment]
@scarlehoff I definitely agree. We should get rid of `theory.db`. Couldn't we just use this https://github.com/NNPDF/theories/tree/main/data/theory_cards? And remove any dependencies on `theory.db` in validphys?

**Comment by Zaharid** [comment]
I think that dumping those theory cards in the nnpdf repo (and changing the docs and the various scripts that read the db) should essentially do the trick. It does involve some work. Also we, would want to have a schema that is as good as the sqlite one (validobj should give us valid theory objects).

FWIW this was one of those things that would happen in Milan many years ago. I am sure it was in one of these blackboards that mysteriously dissipated.

**Comment by scarlehoff** [comment]
> FWIW this was one of those things that would happen in Milan many years ago.

That is basically the cards there https://github.com/NNPDF/theories/tree/main/data/theory_cards it did happen.

**Comment by Zaharid** [comment]
While we are taking, we should think of a way to specify how a thoery relates to another (which sql is good for but oh well). I mean things like scale_variation_for, alpha_s variation for and so on. So we don't have to have some hardcoded piece in an unrelated part, or worse, repeating the information in every runcard and getting it wrong.



> That is basically the cards there https://github.com/NNPDF/theories/tree/main/data/theory_cards it did happen.

except for 

> I think that dumping those theory cards in the nnpdf repo (and changing the docs and the various scripts that read the db) should essentially do the trick. It does involve some work. Also we, would want to have a schema that is as good as the sqlite one (validobj should give us valid theory objects).

**Comment by RoyStegeman** [comment]
How about a simple `.csv` instead? It may be easier to find a nice reader with filter functionality for that (e.g. any excel-like program will do) than for yaml.
