### ISSUE TITLE
Validphys should not use a matplotlib  gui

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#1718]
Currently we initiate figures with

```
import maptplib.pyplot as plt

fig, ax = plt.subplots()
```

instead we should do

```
from matplotlib.figure import Figure

def simple_subplots():
    fig = Figure()
    ax = fig.subplots()
    return fig, ax
```

and not import pyplot anywhere. The reason is that (as @AleCandido pointed out) pyplot maintains a  global state that makes it misbehave in multithreaded applications such when executed under dask. One sees warnings like

```
/home/zah/nngit/nnpdf/validphys2/src/validphys/plotutils.py:307: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
```

as well as initialize some gui bindings that we don't need and have to work around (which is more complicated in multiporcessing  applications such as how we like to run dask).

This is hinted at e.g. in

https://matplotlib.org/stable/gallery/user_interfaces/web_application_server_sgskip.html

AFAICT a big search and replace should have few side effects.

The reportengine example should be tweaked as well, and figure.py should not need calling plt.close.

**Comment by scarlehoff** [comment]
Closed by #1723
