### ISSUE TITLE
Installation with conda not working

### ISSUE THREAD

**Issue by t7phy** [NNPDF/nnpdf#1732]
Since last week monday, it has not been possible to install nnpdf or its dependencies through conda.

The following is what happens:

$ conda install --only-deps nnpdf
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | Killed

Does it have anything to do with the server failure about 2 weeks back? And how to solve this issue?

**Comment by RoyStegeman** [comment]
Oh conda indeed consumes a lot of memory. Was this different until two weeks ago? Mamba works fine though, so I'd recommend just using that.

**Comment by scarlehoff** [comment]
> which is also used by the CI

This is used by the CI for the fit bot which needs to install the local nnpdf package.

The CI for master instead uses the default solver and seems to work ok. However, I do agree that using mamba is probably a good idea as it is so much faster: https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community

**Comment by RoyStegeman** [comment]
The linux CI also no longer uses conda-build, but mamba instead: https://github.com/NNPDF/nnpdf/blob/d056a6fbbd4ddbf5d44b7986110a77eb6e919082/.github/workflows/tests.yml#LL52C9-L52C9

MacOS does still fully use conda though.

**Comment by scarlehoff** [comment]
I didn't mean the building process but the installation (that's why I mentioned master): https://github.com/NNPDF/nnpdf/actions/runs/4949004118/jobs/8850512440#step:9:45 which installs the `nnpdf` package after uploading it to the server.

(note that the solver failed a few times before it managed to install nnpdf from the server)

**Comment by RoyStegeman** [comment]
Oh indeed that's the conda solver. Anyway, I'll assume this worked for @t7phy? If not, feel free to re-open this issue.
