### ISSUE TITLE
Create a test theory for QED and reorganize tests

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/nnpdf#1735]
As mentioned in these two comments

https://github.com/NNPDF/nnpdf/pull/1643/files#r1146321927
https://github.com/NNPDF/nnpdf/pull/1643/files#r1155696692

the tests for the photon should be reorganized and modified so that we are testing something a bit closer to the actual usage. Similar to what is done for other things (like the new cfactors).

This is related #1729 since also Theory 399 needs to be updated to have a small eko to test the info file. I'll coordinate with @niclaurenti to create the new theories and update the tests.

**Comment by niclaurenti** [comment]
@scarlehoff I didn't understand how the `eko.tar` of the low precision theory should be done. Moreover, do we want to produce a low precision `eko_photon.tar` as well?

**Comment by scarlehoff** [comment]
>  do we want to produce a low precision eko_photon.tar as well 

Yes.

> I didn't understand how the eko.tar of the low precision theory should be done

My idea with this is to create an eko with a very small number of points (in Q but also x). The final PDF doesn't need to be sensible, it just needs to look like a PDF from the point of view of the code.
