### ISSUE TITLE
ATLAS_WZ_TOT_13TEV for theory 162

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#1744]
I would like to add a test involving this dataset, but I get

```
from validphys.api import API
API.dataset(dataset_input={'dataset': 'ATLAS_WZ_TOT_13TEV'}, use_cuts='internal', theoryid=162)
```
```
ConfigError: Could not find FKTable for set 'ATLAS_WZ_TOT_13TEV'. File '/home/zah/anaconda3/envs/nnpdfdev/share/NNPDF/data/theory_162/fastkernel/FK_ATLAS_WZ_TOT_13TEV.dat' not found

```

Note that what is really missing is a compound file mapping to

```
FK_ATLASWZTOT13TEV81PB.dat
```

like we have for theory 200.

```
# COMPOUND FK
FK: FK_ATLASWZTOT13TEV81PB.dat
OP: NULL
```

**Comment by scarlehoff** [comment]
Why do you want to have a test for that specific dataset (I'd say just add the compound file... ).

Otherwise, if it doesn't matter where the dataset is coming from, just use theory 399 instead.

```
API.dataset(dataset_input={'dataset': 'ATLAS_WZ_TOT_13TEV'}, use_cuts='internal', theoryid=399)
```

No need for compound files!

**Comment by Zaharid** [comment]
I want a test for that dataset and for that theory. So it would be good to have that file added. I guess this issue is both to ask if there is a reason it's not there and because I'd prefer to have someone else add it.

**Comment by scarlehoff** [comment]
Closing this. New test should use the new theories (of which the low precision one for testing is 399).
