### ISSUE TITLE
crash or warn after many iterations generating negative pseudodata

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/nnpdf#1783]
We have a known issue in the pseudodata generation, if the data generated is (always) negative the pseudodata generation gets stuck in an infinite loop.
In general this means there's a bug either in the commondata or the covmat but I think it would be a good idea to warn the user about a possible cause for why the code looks like its frozen while it's taking 100% of a CPU core.

It might also be a good idea to make the code crash after some number of tries (that can be absurdly large). I think after 10^6 we can safely crash?

This is somewhat related to #1556

**Comment by Zaharid** [comment]
I think this would be an improvement.
