### ISSUE TITLE
Allow for hyperoptimization restart from `tries.json`

### ISSUE THREAD

**Issue by Cmurilochem** [NNPDF/nnpdf#1807]
@APJansen, @goord and myself conducted recently hyperoptimization experiments at multi-replica level using our local Snellius cluster. 

With a limited max wall time (120h in gpu partition), it became clear that the increase in the number of replicas (and consequently increase in the computation time per trial) would result in a relatively poor sample of the hyperparameter space per calculation.

It would be very nice if we could restart the hyperoptimization process using info from a previous `tries.json` file and input seeds.

Not sure whether this option might be easily adapted or considerable changes must be made in `ModelTrainer.hyperparametrizable`. 

I could assign myself for the task but would appreciate any suggestion and thoughts about this issue.

**Comment by Cmurilochem** [comment]
Just saw isse #1800.

**Comment by scarlehoff** [comment]
I'll close it in favor of #1800
RE the multireplicas however, an idea that we had in the past was a trimming of the hyperspace with one replica fits to define a reduced parameter scan.
It was not very relevant in the previous implementation but now it might help.
(of course, only valid for parameters that can be set separately per-replica in parallel, such as the number of epochs or the positivity but not things like the optimizer)
