### ISSUE TITLE
Issues in comparing two fits

### ISSUE THREAD

**Issue by wajidalikhan** [NNPDF/nnpdf#1811]
Dear Experts, 

I am trying to compare two fits: 
`vp-comparison -i`
230217_tutorialfit 
230217_tutorialfit_2

but I end up with the following error. Could you please help me in this regard, please. 

`ValueError: 'yerr' must not contain negative values``

`/tmp/validphys-crash-56a01v5s`

Regards, Wajid

**Comment by scarlehoff** [comment]
Hi @wajidalikhan, thanks for your question. Could you give us a few details

Which version of the code are you using (you can do for instance: 
```
python -c "import validphys as vp ; print(vp.__version__)"
```

**Comment by Radonirinaunimi** [comment]
Without having full access to the logs, I could only guess. This issue **usually** arises when you have negative `yerr` in the following lines:
https://github.com/NNPDF/nnpdf/blob/0a1446a5965972f95c8b0b3a24b50072aab27153/validphys2/src/validphys/dataplots.py#L1019-L1028

You could ofc easily bypass this taking the `abs` of the differences (for the sake of getting the report) but this might not make much sense. There might be something weird with the fit.

**Comment by wajidalikhan** [comment]
Hi @scarlehoff, @Radonirinaunimi, 

Thank a lot for your help. The code version that at the moment I use is: 
```
python -c "import validphys as vp ; print(vp.__version__)"
4.0.6.26+gbea644cfb
```
and the full error log that I get is copied below: 

```
(base) wajid@OptiPlex-7080:~/packages/nnpdfgit/reports$ vp-comparefits -i
Enter current fit: 230217_tutorialfit
Enter reference fit: 230217_tutorialfit_2
Enter report title [default:
Comparison between 230217_tutorialfit and 230217_tutorialfit_2 ]:
 
Enter author name: wajid,,,
Enter keywords:
Enter label for current fit [default:
Current Fit]:
 
Enter label for reference fit [default:
Reference Fit]:
 
[INFO]: Starting NNPDF fit comparison:
    Current fit: 230217_tutorialfit
    Reference fit: 230217_tutorialfit_2
    Title: Comparison between 230217_tutorialfit and 230217_tutorialfit_2 
    Author: wajid,,,
    Keywords: []
    Current fit label: Current Fit
    Reference fit label: Reference Fit
    Thcovmat if present: False
[WARNING]: Output folder exists: /home/wajid/packages/nnpdfgit/reports/output Overwriting contents
[INFO]: All requirements processed and checked successfully. Executing actions.

----

Traceback (most recent call last):
  File "/home/wajid/miniconda32/bin/vp-comparefits", line 10, in <module>
    sys.exit(main())
  File "/home/wajid/miniconda32/lib/python3.10/site-packages/validphys/scripts/vp_comparefits.py", line 236, in main
    a.main()
  File "/home/wajid/miniconda32/lib/python3.10/site-packages/reportengine/app.py", line 395, in main
    self.run()
  File "/home/wajid/miniconda32/lib/python3.10/site-packages/validphys/app.py", line 159, in run
    super().run()
  File "/home/wajid/miniconda32/lib/python3.10/site-packages/reportengine/app.py", line 380, in run
    rb.execute_sequential()
  File "/home/wajid/miniconda32/lib/python3.10/site-packages/reportengine/resourcebuilder.py", line 166, in execute_sequential
    result = self.get_result(callspec.function,
  File "/home/wajid/miniconda32/lib/python3.10/site-packages/reportengine/resourcebuilder.py", line 175, in get_result
    fres =  function(**kwdict)
  File "/home/wajid/miniconda32/lib/python3.10/site-packages/validphys/dataplots.py", line 1022, in plot_dataspecs_positivity
    return plot_positivity(
  File "/home/wajid/miniconda32/lib/python3.10/site-packages/validphys/dataplots.py", line 980, in plot_positivity
    ax.errorbar(
  File "/home/wajid/miniconda32/lib/python3.10/site-packages/matplotlib/__init__.py", line 1423, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/wajid/miniconda32/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 3595, in errorbar
    raise ValueError(
ValueError: 'yerr' must not contain negative values

----

[CRITICAL]: A critical error ocurred. This is likely due to one of the following reasons:

 - A bug in validphys.
 - Corruption of the provided resources (e.g. incorrect plotting files).
 - Cosmic rays hitting your CPU and altering the registers.

The traceback above should help determine the cause of the problem. If you
believe this is a bug in validphys (please discard the cosmic rays first),
please open an issue on GitHub<https://github.com/NNPDF/nnpdf/issues>,
including the contents of the following file:

/tmp/validphys-crash-56a01v5s
```
If Could you please point me to the input cards that you used to generate these fits I can try generating these two fits again and try the compare the results. Or I can try to compare any FitA with it-self, i.e., FitA vs FitA. What do you think?

**Comment by wajidalikhan** [comment]
Also, it happens many times that the `evolven3fit` get killed, Is there any specific reason, why its getting killed by the system.

```
evolven3fit fit1 5
.
.
.
 Qi = 1.65 -> Qt = 3.88008 GeV
-------------------------
 Qi = 1.65 -> Qt = 4.35845 GeV
-------------------------
 Qi = 1.65 -> Qt = 4.92 GeV
-------------------------
Killed

```

**Comment by Radonirinaunimi** [comment]
Hi @wajidalikhan, the error you are seeing is exactly what I described above (although the exact lines slightly differ: yours is at line `980` while in current master it is at line `1019`). 

You can see all the input cards used to produce the (published) fits in the folder [n3fit/runcards/reproduce_nnpdf40](https://github.com/NNPDF/nnpdf/tree/master/n3fit/runcards/reproduce_nnpdf40), and in particular you may want to use [NNPDF40_nnlo_as_01180_1000.yml](https://github.com/NNPDF/nnpdf/blob/master/n3fit/runcards/reproduce_nnpdf40/NNPDF40_nnlo_as_01180_1000.yml).

As for the `evolven3fit`, I think that you don't have enough resources (are you running it on your own laptop?).

**Comment by wajidalikhan** [comment]
Hi @Radonirinaunimi, thank you for your help. Changing `yerr=[cv - lower, upper - cv], ` to  `yerr=[abs(cv - lower), abs(upper - cv)],`

still points to the same error. I am using the desktop and yes killing other things running in the background helps to resolve.

**Comment by wajidalikhan** [comment]
Hi, any other suggestion or comment which can help to rectify the problem?

**Comment by RoyStegeman** [comment]
> But I re-iterate, this is just an ad-hoc fix and you might want to re-run a proper fit.

Pleas only remember this - there is clearly something wrong with the input so hacking the code to avoid an error that's there for a reason is not the way to go. 

Did you produce the runcards for your fits by yourself, or are they taken directly from https://github.com/NNPDF/nnpdf/tree/master/n3fit/runcards/examples?

Maybe it's wisest to follow the instructions in the docs to run a fit using the [`Basic_fit.yml` runcard](https://github.com/NNPDF/nnpdf/blob/master/n3fit/runcards/examples/Basic_runcard.yml)  since that's computationally light. Once that works and you can produce a report comparing two such fits, you can then move on to doing the default nnpdf4.0 fit [NNPDF40_nnlo_as_01180_1000.yml](https://github.com/NNPDF/nnpdf/blob/master/n3fit/runcards/reproduce_nnpdf40/NNPDF40_nnlo_as_01180_1000.yml) that @Radonirinaunimi proposed, or whatever settings you'd be interested in trying yourself.

**Comment by wajidalikhan** [comment]
Hi RoyStegeman, @Radonirinaunimi, 

Thank you very much for your help. Yes, that is just an adhoc solution. Following @RoyStegeman suggestion I got the [Basic_runcard](https://github.com/NNPDF/nnpdf/blob/master/n3fit/runcards/examples/Basic_runcard.yml) and made two copied of it `fit1` and `fit2` and the only difference between `fit1` w.r.t to `fit2` is `wptcut_lhc   : 30.0` changed to `wptcut_lhc   : 40.0` 

but unfortunately it complains the same for lets say 6 replicas.  

`ValueError: 'yerr' must not contain negative values`

**Comment by RoyStegeman** [comment]
I've never seen that error before, and while it must be unlikely, the only explanation I can think of right now are finite size effects. I say this because `cv` corresponds to the prediction for that (pseudo-)observable made using the average PDF replica (i.e. the averaging over replicas for `cv` is done at the PDF level as opposed to the prediction level). So if you have the resources for it, you may want to increase the number of replicas and see if the error persists. 

Also `wptcut_lhc` has been deprecated so those to fits are the same. This is not a problem for this check though since you could even compare a PDF fit to itself.

To see if you can perhaps understand what's going on you may want to have a look at the PDFs themselves, that's something you can do for example by running `validphys runcard.yaml` using the following runcard:

```
meta:
    author: Wajid Ali Khan
    title: PDF plots 
    keywords: [test]

pdfs:
  - {id: 230217_tutorialfit}
  - {id: 230217_tutorialfit_2}

PDFscalespecs:
  - xscale: log
    Xscaletitle: Log
  - xscale: linear
    Xscaletitle: Linear

Basespecs:
  - basis: flavour
    Basistitle: Flavour basis
  - basis: evolution
    Basistitle: Evolution basis

Qs:
  - Q: 1.651
  - Q: 100

template_text: |
  % comparing pdfs
  {@with Qs@}
  # Q = {@Q@} GeV

  ## Uncertainty bands
  {@with Basespecs@}
  ### {@Basistitle@}
  {@with PDFscalespecs@}
  #### {@Xscaletitle@}
  {@plot_pdfs@}
  {@endwith@}
  {@endwith@}

  ## Replicas
  {@with Basespecs@}
  ### {@Basistitle@}
  {@with PDFscalespecs@}
  #### {@Xscaletitle@}
  {@plot_pdfreplicas@}
  {@endwith@}
  {@endwith@}
  {@endwith@}

actions_:
  - report(main=True)
```

**Comment by wajidalikhan** [comment]
Hi @RoyStegeman, I generated about 100 replicas using the [Basic_runcard](https://github.com/NNPDF/nnpdf/blob/master/n3fit/runcards/examples/Basic_runcard.yml), I also checked if there is anything funny going on with the run card that you gave above. I don't know why but it still complains the same :( i.e., the issue persists.

**Comment by wajidalikhan** [comment]
BTW what is the difference between [validphys 2](https://docs.nnpdf.science/vp/index.html) and `validphys`

**Comment by Radonirinaunimi** [comment]
@wajidalikhan Although I have encountered the exact error you are seeing before, I have never encountered it when using the example cards (in particular the `Basic_runcard`). Have you tried to run @RoyStegeman's proposal above regarding the PDFs comparisons only?

**Comment by wajidalikhan** [comment]
Hi @Radonirinaunimi, Yes, I have tried the @RoyStegeman's proposal and I don't see anything funny, I tried with the already produced PDF and they both tend to behave more or less the same.

**Comment by Radonirinaunimi** [comment]
@wajidalikhan, I think various people (@goord, @APJansen) have run a proper fit with `Basic_runcard` and never experienced such issue. Would it be possible for you to upload the fit on Dropbox for example such that we can have a look and try to understand what's going on?

**Comment by wajidalikhan** [comment]
Hi @Radonirinaunimi, Thanks a lot.  I downgraded the python version  `Python 3.9.18` fixes the crash at-least. And a quick search on google pointed to the fact the `matplotlib 3.7.2` or lower should not give this problem. I am not quite sure how well established this is but apparently it fixes the issue. 

May be you / some else could comment better if that could be really an issue.

**Comment by scarlehoff** [comment]
Thinking about this, there's a situation in which that error can be triggered which is not actually a bug (or a bad input), which is a situation in which the errors are 0 in one side (whatever combination cv == lower == upper).

This would be strange in a normal dataplot but your error is specific to the positivity plots

```
  File "/home/wajid/miniconda32/lib/python3.10/site-packages/validphys/dataplots.py", line 1022, in plot_dataspecs_positivity
    return plot_positivity(
```

which is the one that I would guess is prone to that issue.

So maybe we do want to put a `np.abs(` around the error bands or at least a check on the size of the negativity @RoyStegeman @Radonirinaunimi

**Comment by Radonirinaunimi** [comment]
> Thinking about this, there's a situation in which that error can be triggered which is not actually a bug (or a bad input), which is a situation in which the errors are 0 in one side (whatever combination cv == lower == upper).
> 
> This would be strange in a normal dataplot but your error is specific to the positivity plots
> 
> ```
>   File "/home/wajid/miniconda32/lib/python3.10/site-packages/validphys/dataplots.py", line 1022, in plot_dataspecs_positivity
>     return plot_positivity(
> ```
> 
> which is the one that I would guess is prone to that issue.
> 
> So maybe we do want to put a `np.abs(` around the error bands or at least a check on the size of the negativity @RoyStegeman @Radonirinaunimi

Regarding this specific scenario you mentioned above, I'd be fine doing so provided that (for the record) we output warnings saying that the values were negatives. 

That being said, I'd still be curious to look at @wajidalikhan's fits to understand exactly what is going on. It is a bit strange to me that downgrading `matplotlib` solved the issue (or maybe it is related to the specific scenario you mentioned @scarlehoff).

> Would it be possible for you to upload the fit on Dropbox for example so that we can have a look and try to understand what's going on?

**Comment by RoyStegeman** [comment]
> So maybe we do want to put a np.abs( around the error bands or at least a check on the size of the negativity

I don't think this makes any sense, and even if it did, if we don't raise an error we won't even be aware that something was wrong since I don't check the logs if I get my report seemingly without any problem.  This is also why I think outputting a simple warning as suggested by @Radonirinaunimi is not a good idea.

But mostly, I don't think it makes any sense to do this as it will mess up the interpretation of whatever result we get.

> That being said, I'd still be curious to look at @wajidalikhan's fits to understand exactly what is going on.

If @wajidalikhan got his report working in the end and is happy with it, I am too :) - I have other things that I'd rather spend my time on. Having said that, I do agree with the sentiment that what happened is strange and I'd be somewhat interested to understand what caused it. In particular considering I must have run O(100) different setups in the past years and never encountered this error, while now it occurs with THE setup that I often use for a quick first check.

**Comment by scarlehoff** [comment]
I'll take that as a no :P 

> I don't think this makes any sense

```
plt.errorbar([0.4], [0.5], yerr=[ [-1e234], [0.3] ])
```

That will throw the error and things like positivity can get that kind of numbers. Specially in some edge cases such as a saturated PDF. Too restrictive cuts, etc.
But I take your point that this would still be pointing to something being wrong and that the error is preferred.

**Comment by wajidalikhan** [comment]
Hi @scarlehoff, @Radonirinaunimi , @RoyStegeman, thank you very much for your comments and suggestion. It solves the issue but still remains to see / or to find out if that was really the case and there is nothing wrong. 

BTW I can copy the grids / fits / logs if anyone of you is interested to look or suggests me to do some other checks I can do them to understand it more. 

BTW could you please point me to the snip to compare two PDFs only, Not the fits but just to compare two / three pdf luminosities / distances etc in the case I don't have their fit results but just the pdfs.

**Comment by RoyStegeman** [comment]
Hi @wajidalikhan, if you could put the LHAPDF grids (or even better, the full fit folder) somewhere such that we can have a look that would be greatly appreciated.

Below is a snippet to compare luminosities using the PDFs (i.e. LHAPDF grid files) as opposed to requiring a full fit, the snippet I shared earlier does the same for PDFs. Of course you can combine both in a single report as well, or change settings or add/remove stuff as you like, but it should give you a starting point. 

```
meta:
    author: Wajid Ali Khan
    title: Lumi plots 
    keywords: [luminosity]


pdfs:
  - {id: 230217_tutorialfit, label: "first fit"}
  - {id: 230217_tutorialfit_2, label: "second fit"}

sqrts: 13000 # GeV

lumi_channels:
  - gg
  - gq
  - qq
  - qqbar
  - uubar
  - ddbar
  - ssbar
  - ccbar
  - bbbar
  - udbar
  - dubar
  - scbar
  - csbar
  

PDFscalespecs:
  - xscale: log
    xscaletitle: Log
    ymin: 0.85
    ymax: 1.15

template_text: |
  {@with PDFscalespecs@}
  {@xscaletitle@} scale
  =====================
  {@with lumi_channels@}
  {@plot_lumi1d(normalize_to=2)@}
  {@endwith@}
  {@endwith@}
  
actions_:
  - report(main=True)

```

**Comment by RoyStegeman** [comment]
Thanks @wajidalikhan for sharing your fits. I don't see anything worrying in the PDFs, and I'm also able to calculate the positivity observables used during the fit without any problems. In terms of PDFs, the charm (see below) shows some of the behaviour that would lead to the error you observe, and trying to calculate POSF2C indeed does raise that error. 

While it is strange that the matplotlib version makes a difference, the behaviour I observed during this check is exactly as expected. To not waste time on this I suggest we consider this issue dealt with at least until more people run into the same problem. 

![image](https://github.com/NNPDF/nnpdf/assets/57906554/0fda4754-55f1-4f70-93ab-7ea434941577)
