### ISSUE TITLE
Restart Hyperopt from pickle `tries.pkl` file

### ISSUE THREAD

**Issue by Cmurilochem** [NNPDF/nnpdf#1815]
In [restart_hyperopt]( https://github.com/NNPDF/nnpdf/tree/restart_hyperopt) and PR #1812, I've made some changes to allow us conduct hyperoptimization restarts. By adding some extra methods to the `FileTrials` class, we are for the moment able to restart jobs using a pickle `tries.pkl` file that is currently used  to: 
- save final states of `FileTrials` after all trials in case of a normal job.
- initiate the state of `FileTrials` to that of a previous run in case of restarts, e.g, using `initial_filetrials = FileTrials.from_pkl(tries.pkl)`.

Would this fulfil our requirements for the moment ? I am also currently trying to add an extra `@classmethod` to the `FileTrials` class, e.g., `filetrials = FileTrials.from_json(tries.json, *args, **kwargs)` that could also be used for restarting in addition to `tries.pkl`. But I am facing some initial difficulties due to the special formatting and encodings present in `tries.json`. Not sure if the restart from json would possible or even sustainable as this could no longer work in case of any future changes in our current json structure. Please, I would appreciate any suggestions or comments.

**Comment by Radonirinaunimi** [comment]
Hi @Cmurilochem, will you be in Science Park tomorrow (or early next week) such that we can discuss how this should be exactly done? Otherwise, zoom will also be fine.
