### ISSUE TITLE
Pineappl FkTable reader fails for new Jet grids

### ISSUE THREAD

**Issue by comane** [NNPDF/nnpdf#1829]
When trying to load a theory 600 pineappl grid such as ATLAS_1JET_8TEV_R06_PTY_BIN1.pineappl.lz4 using:

`pineappl.fk_table.FkTable("ATLAS_1JET_8TEV_R06_PTY_BIN1.pineappl.lz4")`

I get the following error

```
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
File /var/folders/h8/rpdyzfjj6bv49nxrm1s22g1c0000gn/T/ipykernel_48719/2477570161.py:1
----> 1 FkTable.read("/Users/markcostantini/local/nnpdf_data/theory/theory_600/fastkernel/ATLAS_1JET_8TEV_R06_PTY_BIN1.pineappl.lz4")

File ~/miniconda3/envs/nnpdf-dev/lib/python3.9/site-packages/pineappl/fk_table.py:35, in FkTable.read(cls, path)
     18 @classmethod
     19 def read(cls, path):
     20     """
     21     Load an existing grid from file.
     22 
   (...)
     33             grid object
     34     """
---> 35     return cls(PyFkTable.read(path))

PanicException: called `Result::unwrap()` on an `Err` value: NonUniqueGrids
```

Maybe @scarlehoff  and @t7phy  can help with this?

**Comment by scarlehoff** [comment]
Create a PR against #1813 so that I can have a look because there are many possible reasons for this error:

1. Is the `metadata.yml` on the new dataset correct?
2. Is the theory part of the `metadata.yml` of the new dataset correct?
3. Does the fktable exist at all?
4. Is your version of theory 600 up to date?
5. Is this an error of current theory 600?

**Comment by comane** [comment]
I am not sure that the  `metadata.yaml` matters at all for this issue. I am trying to load directly the pineappl file contained In the most up to date version of theory 600
```
from pineappl.fk_table import FkTable
FkTable.read("/path_to_theory_600/fastkernel/ATLAS_1JET_8TEV_R06_PTY_BIN1.pineappl.lz4")
```

**Comment by t7phy** [comment]
@scarlehoff No I actually added the fktables for the old jets too because these are the new grids (at NNLO)

**Comment by scarlehoff** [comment]
And can you read those locally using the code @comane put in his comment?

**Comment by t7phy** [comment]
I haven't tried with validphys. I know they were with pineapl cli though. So they should be fine.

**Comment by scarlehoff** [comment]
No, that's not validphys, that's the python interface of pineappl.

If they work with the cli and not with the python interface it's a bug of pineappl.

However, another possibility is that either @t7phy  or @comane are not using the latest pineappl version.

**Comment by comane** [comment]
The version I am using is:

>>> import pineappl
>>> pineappl.__version__
'0.5.9'

**Comment by t7phy** [comment]
@scarlehoff tbh I did not look at the above code, I was told my @comane that he was using it with validphys
@comane thats an old versionm try updating it

**Comment by comane** [comment]
@scarlehoff @t7phy , thank you, indeed upgrading solved the issue.

>>> pineappl.__version__
'0.6.0'
