### ISSUE TITLE
Sort dataset diffs

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/nnpdf#1858]
Can we please sort [Dataset differences and cuts](https://vp.nnpdf.science/WyHREKMwQiyD2lXbmWFV4Q==/#dataset-differences-and-cuts)? with whatever unique sort you like - e.g. alphabetic ... else I can only guess by the length that this is the same as in [this report](https://vp.nnpdf.science/XiaPwCL9QjiQW0TOvlVpCw==/#dataset-differences-and-cuts)

I guess it should be somewhere here:
https://github.com/NNPDF/nnpdf/blob/ce6c05cacec95dee36c577503c9a1109daa2908a/validphys2/src/validphys/fitdata.py#L296

**Comment by scarlehoff** [comment]
> else I can only guess by the length that this is the same

I'm a bit confused. When they are not the same you get a list of things that are different, e.g.: https://vp.nnpdf.science/BMvnWVZaRSGjBF9mAzFKiQ==/#dataset-differences-and-cuts

**Comment by felixhekhorn** [comment]
report 1 is A vs. B and report 2 is C vs. D - if possible I'd like to catch in a glance that they don't differ by dataset but by theory setting

**Comment by felixhekhorn** [comment]
Adding more (relevant) information is a good I idea I think ... but I ask for a small (i.e. quick) improvement first :innocent:
