### ISSUE TITLE
Error in comparing two fits in NNPDF determination

### ISSUE THREAD

**Issue by TheWaleedHussain** [NNPDF/nnpdf#1860]
I am trying to compare two fits using command "vp-comparefits -i"  but everytime I'm getting same error. I have tried to run this command by using different python versions but it is still not working. Tell me what to do now. Here is the error that I'm getting:

![Error](https://github.com/NNPDF/nnpdf/assets/146311717/e6d6b4e3-4a66-4bc3-aeb0-75fdd90f9420)

**Comment by scarlehoff** [comment]
Could you tell us the version of the code you are using?

If you could upload somewhere the fit(s) that are  producing this errors so that we can reproduce them that would be really helpful. Thanks.

**Comment by TheWaleedHussain** [comment]
I am using the following version of code:

`python -c "import validphys as vp ; print(vp.__version__)"
4.0.7.4+gce6c05cac`

I am trying to compare these two fits:

`230217_tutorialfit` : (https://data.nnpdf.science/fits/230217_tutorialfit.tar.gzl)
`230217_tutorialfit_2` : (https://data.nnpdf.science/fits/230217_tutorialfit_2.tar.gz)

**Comment by scarlehoff** [comment]
Many thanks for the report. This is fixed in PR #1868 

For the time being I 've updated the `230217_tutorialfit` so that it is a bit more smooth and it should not produce the error any longer.
