### ISSUE TITLE
Failing `test_restart_from_pickle` in `n3fit/tests/test_hyperopt.py`

### ISSUE THREAD

**Issue by Cmurilochem** [NNPDF/nnpdf#1885]
It seems that the test [test_restart_from_pickle](https://github.com/NNPDF/nnpdf/blob/adcad92ea6f9c5522b626510468acecddab1d1fc/n3fit/src/n3fit/tests/test_hyperopt.py#L34C5-L34C29) created by me fails occasionally. The reason is that, because we calculate too few trials (2 and then 4) in the hyperopt, it may happen that none of the trials end up with a `hyper_loss` below the threshold; this is certainly not in the scope of the test itself and might be slightly annoying.

To correct for that I suggest:
- increasing the number of trials and/or epochs (which might not directly solve the problem a priori with added timings)
- increasing the k-fold hyper opt threshold [here](https://github.com/NNPDF/nnpdf/blob/adcad92ea6f9c5522b626510468acecddab1d1fc/n3fit/src/n3fit/tests/regressions/hyper-quickcard.yml#L74) in the `hyper-quickcard.yml` file
- create a specific runcard for this test and add a high threshold since here we are only interested in asserting that the final `json` files are equivalent and show the same number (regardless their magnitude).

Which one would be the best alternative ? Please, also feel free to suggest any other alternative.

**Comment by RoyStegeman** [comment]
To be honest, I can't say I've noticed it failing yet, so I guess it doesn't happen that often. Since this is not a regression test, and the main point of this test is to see if the restart functionality works I'd say increasing the threshold is fine.

> I think the actual problem then is that the results are not reproducible? Two runs of the same runcard should produce the same result if the seeds are the same.

As the fitbot also shows, fits may change numerically over time (due to change in dependencies or whatever. I'm not sure this is the test we want to fail due to such things though.

**Comment by RoyStegeman** [comment]
This is a hyperopt using three datasets (and thus fits to one and two datasets), I could imagine that can make it quite unstable. 

Having said that, perhaps it's indeed worth checking if two runs with the same environment produce exactly the same results.

**Comment by Cmurilochem** [comment]
I agree. I remember @APJansen having some issues with it this week and I am also having it in #1726 now after updating my branch with master. However, it was ok before. 

I will check carefully as suggested and report the results here soon.

**Comment by RoyStegeman** [comment]
Ah so when you said the test failed occasionally you had just observed it in the `hyperopt_loss` branch (where I indeed now notice the same error in the CI log)?

It seems that the loss is always above 2, even in master, though this indeed shouldn't mean we can't still use these negative results to restart hyperopt.

**Comment by Cmurilochem** [comment]
That is true. I agree @RoyStegeman. Yes, I think I was biased by only looking at `hyperopt_loss` and also remember Aron with a similar problem this week. I am investigating what is going on in `hyperopt_loss`. It should pass with the same config as master (I suppose so!). Thanks once again!

**Comment by APJansen** [comment]
@Cmurilochem I think my issues were not due to this, after fixing something (don't remember now what, but definitely unrelated to the issue here), it passed and I haven't seen it fail without explanation.
