### ISSUE TITLE
Printing Multi-statistics to hyperopt json files

### ISSUE THREAD

**Issue by Cmurilochem** [NNPDF/nnpdf#1894]
This would be an extension of #1726 and a direct application of the newly implemented `HyperLoss` class. 

Despite opting for a specific statistics whose values are used as metrics for the hyperoptimization, it would be nice to also be able to print all statistics, i.e., `average`, `best_worst` and `std`, for `hyper_loss` (and possibly for `validation_loss` and `experimetal_loss`) in the json file. For this we would need to adapt and instantiate `HyperLoss` several times.

**Comment by goord** [comment]
Maybe we can print a matrix (folds x replicas) of chi-square values and a vector (folds) of phi values. From these building blocks all current losses can be reconstructed.
