### ISSUE TITLE
Anticipate how POS FK tables are parsed in the new commondata reader

### ISSUE THREAD

**Issue by Radonirinaunimi** [NNPDF/nnpdf#1908]
I am not entirely sure yet how the positivity FK tables will be parsed in the new commondata reader. At one of the CMs, it was proposed to read the $(x, Q^2)$ info from the FK tables directly therefore removing the need for a commondata file. However, it might still be better (and more flexible) to parse the positivity exactly in the same way as experimental data (as in the old commondata way). This is especially crucial for the polarised fit in which a positivity dataset is composed of compound FK tables with non-`null` operation.

**Comment by scarlehoff** [comment]
This is now implemented in https://github.com/NNPDF/nnpdf/pull/1678/commits/ea06b2d2c86fa25ea14ca4e85eafeb8049a69138

It is not necessary to define data or uncertainties, only kinematics and the number of datapoints.

**Comment by Radonirinaunimi** [comment]
Thanks a lot for this! I've tested and the reading of the FK tables are fine, however, there is still one small issue remaining which is the passing of the `operation` into the positivity object. Currently, even if  `operation` is not `null` in the metadata, `operation_name` is still `NULL`. If you want, I could also try take care of this.

**Comment by scarlehoff** [comment]
I don't underdstand what you mean? Operation name should be read directly. Can you send me the metadata failing?

**Comment by Radonirinaunimi** [comment]
At the moment, if I catch the `operation_name` from the following line, for example:
https://github.com/NNPDF/nnpdf/blob/ec7640473d393df6db0ff3870e2bb9a21b350cd0/n3fit/src/n3fit/model_gen.py#L175
the value is always `NULL` for positivity dataset regardless of what is defined in the metadata.

> Can I reproduce it by simply adding an op?

Yes, you can reproduce the behavior by taking one of the POS data that you converted and add just `operation` under theory.

**Comment by scarlehoff** [comment]
ok, found it. It is read ok but at some point vp drops operations from positivity and integrability. It will be fixed in the next commit in a few minutes.

**Comment by Radonirinaunimi** [comment]
Awesome, thanks! Tested it and it works fine.
