### ISSUE TITLE
Kinematic Coverage (x-q) plot (will be) broken

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/nnpdf#1934]
The x-q2 plot depended on the _exact_ order of the kinematic variables to work and, together with that, the adequate kinematic transformation.

Since the values of x/q for a given dataset are not going to change, I suggest we should include them as part of the `kinematics.yaml` so that _all_ `kinematics.yaml` have a `coverage_Q2` and `coverage_x` entries (or just `Q2` / `x` when it makes sense and it is not an approximation, like with DIS).

By doing this:
1. We have the explicit calculation in the `filter.py` file 
2. We don't need `kinematics_override`, we save all kinematics we need.

Sadly (@t7phy @comane) this means you will need to update the datasets you already implemented so that they can be used with the new commondata.

@Radonirinaunimi the DY datasets seems to be mostly working, I guess you followed the same order they had before.

Note that this is something that affects both the ported commondata but also new datasets that you might want to implement. Without these variables it won't be possible to create the kinematic coverage plot.

A second option is to add a new key to the metadata files, similar to the `kinematic_override` but not making it _explicit_ and _only_ for the xQ2 mapping. So we have a key for `mapping_xq` and we add the relevant functions for that.
This is with the idea that `kinematics_override` will eventually be only for legacy datasets.

**Comment by Radonirinaunimi** [comment]
Yes, I did follow exactly the previous ordering.
