### ISSUE TITLE
CI issue fixed in boa

### ISSUE THREAD

**Issue by APJansen** [NNPDF/nnpdf#1935]
The issue in the CI from two weeks ago arising from boa has been [solved](https://github.com/mamba-org/boa/pull/393), so probably our own fix of it in #1932 can be reverted. Feel free to close/ignore if you think it's not important.

**Comment by scarlehoff** [comment]
If you want to try and remove the pins from the mac build feel free.

The rest can stay, at the end of the day we just updated the workflows to the latests versions and set the default to conda foge (which I need for the time being because of cern policies)
