### ISSUE TITLE
Validphys is not able to deal with PDF sets with `ErrorType: replicas+as`

### ISSUE THREAD

**Issue by giacomomagni** [NNPDF/nnpdf#1956]
When trying to use a PDF set that contains `ErrorType: replicas+as` I get the following error:

```
[ERROR]: Bad configuration encountered:
No Stats class for error type replicas+as
```

This is because such error type is not implemented in `validphys`, so rather 
than a bug this is a feature request.

**Comment by RoyStegeman** [comment]
What should the expected behaviour be for the +as replica(s)?

**Comment by felixhekhorn** [comment]
to replicate the LHAPDF behaviour, no? see [config](https://lhapdf.hepforge.org/config.html) and code [here](https://gitlab.com/hepcedar/lhapdf/-/blob/main/src/PDFSet.cc?ref_type=heads#L77) or [here](https://gitlab.com/hepcedar/lhapdf/-/blob/main/src/PDFSet.cc?ref_type=heads#L229)
