### ISSUE TITLE
Problem with conda installation on Mac M3

### ISSUE THREAD

**Issue by mariaubiali** [NNPDF/nnpdf#1967]
Hi all, I am trying to install the nnpdf code on my new mac (M3) and I fail. 
I have this message
```
Downloading conda
 % Total  % Received % Xferd Average Speed  Time  Time   Time Current
                 Dload Upload  Total  Spent  Left Speed
 0   0  0   0  0   0   0   0 --:--:-- --:--:-- --:--:--   0
100 103M 100 103M  0   0 22.7M   0 0:00:04 0:00:04 --:--:-- 25.8M
Entering conda installer.
WARNING:
  Your operating system appears not to be 64-bit, but you are trying to
  install a 64-bit version of Miniconda3.
  Are sure you want to continue the installation? [yes|no]
```
If I say “yes” I get this error message
`/var/folders/db/q9tyvhkx57v96mhzy47yp6wm0000gn/T/conda_downloadXXXXXXXXX.pqPHIX6cca/conda_installer.sh: line 1242: /Users/mariaubiali/hep/miniconda3/_conda: Bad CPU type in executable`

Has anybody had this issue before?

**Comment by scarlehoff** [comment]
If I look at the system requirements of [conda](https://docs.anaconda.com/free/miniconda/miniconda-system-requirements/#system-requirements) it mentions only M1 so maybe it doesn't know what to do with M3...

You can try with the arm installation (instead of the x86 one) ([docs](https://docs.anaconda.com/free/miniconda/#quick-command-line-install))

```bash
mkdir -p ~/miniconda3
curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh -o ~/miniconda3/miniconda.sh
bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
rm -rf ~/miniconda3/miniconda.sh
```

and hope for the best...

**Comment by Radonirinaunimi** [comment]
> You can try with the arm installation (instead of the x86 one) ([docs](https://docs.anaconda.com/free/miniconda/#quick-command-line-install))

But I think the error was that it is trying to install the `x86` conda while the architecture was still `arm64`. If so, wouldn't the easiest option to change the architecture to `x86` first?

**Comment by scarlehoff** [comment]
The installer is supposed to do that automatically. At least it does in my M1.

(maybe rosetta is not automatically found/installed? `softwareupdate --install-rosetta --agree-to-license` )

**Comment by mariaubiali** [comment]
Thanks a lot! It works! I can update the installation notes on the nnpdf documentation right now. Shall I open a pull request with the changes I'd perform?

**Comment by scarlehoff** [comment]
Yes please!

**Comment by Radonirinaunimi** [comment]
Why is it also not using the python from the conda environment?

**Comment by mariaubiali** [comment]
@Radonirinaunimi I am not sure about it and how to make it work...

**Comment by RoyStegeman** [comment]
> I think we need to stop using recommonmark 

Indeed, this has been a goal for a long time now. Perhaps this is a signal we should finally make our docs `rst` only

**Comment by scarlehoff** [comment]
For the time being there are other stuff that don't work in python 3.12 anyway so anyone using conda should do

```bash
conda create -n python_311_env pyhton=3.11
```

That said, porting the documentation from `.md` to `.rst` is a good starting project since it requires reading the docs a bit (even if just to check that nothing crashes) and some stuff could be fixed during the process.

**Comment by mariaubiali** [comment]
Hi @scarlehoff I did create the environment by using` conda create -n nnpdf_env python=3.11`  but I still get the error message, and I do not understand why the syste is lloking for python 3.12, when I specify the version 3.11

```
Traceback (most recent call last):
  File "/Users/mariaubiali/hep/miniconda3/lib/python3.12/site-packages/sphinx/config.py", line 358, in eval_config_file
    exec(code, namespace)  # NoQA: S102
    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mariaubiali/hep/nnpdfgit/nnpdf/doc/sphinx/source/conf.py", line 18, in <module>
    from recommonmark.transform import AutoStructify
ModuleNotFoundError: No module named 'recommonmark'
```

**Comment by scarlehoff** [comment]
oh, that's strange

If you simply `python`  do you get 3.11 or 3.12?

**Comment by RoyStegeman** [comment]
> File "/Users/mariaubiali/hep/miniconda3/lib/python3.12/

This looks like the environment was not activated, did you do `conda activate nnpdf_env`?

**Comment by Radonirinaunimi** [comment]
> Why is it also not using the python from the conda environment?

This is exactly what I was surprised about here. Somehow it is not using the right python.

@mariaubiali What do you get here when you run the following?

```bash
echo $CONDA_PREFIX
```

And

```bash
python --version
```

**Comment by mariaubiali** [comment]
Indeed, I deactivated and then activated the environment and it works now.... weird :-) 

Now I have another issue but trying to google it and sort it out. FYI

```
(nnpdf_env) MacBook-Pro:sphinx mariaubiali$ make html
sqlite3 -header -csv ../../validphys2/src/validphys/datafiles/theory.db "select * from TheoryIndex;" > source/theories.csv
Creating file ./source/modules/validphys/validphys.rst.
Creating file ./source/modules/validphys/validphys.closuretest.rst.
Creating file ./source/modules/validphys/validphys.compareclosuretemplates.rst.
Creating file ./source/modules/validphys/validphys.comparefittemplates.rst.
Creating file ./source/modules/validphys/validphys.cuts.rst.
Creating file ./source/modules/validphys/validphys.cuts.lockfiles.rst.
Creating file ./source/modules/validphys/validphys.datafiles.rst.
Creating file ./source/modules/validphys/validphys.deltachi2templates.rst.
Creating file ./source/modules/validphys/validphys.hyperplottemplates.rst.
Creating file ./source/modules/validphys/validphys.mplstyles.rst.
Creating file ./source/modules/validphys/validphys.paramfits.rst.
Creating file ./source/modules/validphys/validphys.photon.rst.
Creating file ./source/modules/validphys/validphys.plotoptions.rst.
Creating file ./source/modules/validphys/validphys.scalevariations.rst.
Creating file ./source/modules/validphys/validphys.scripts.rst.
Creating file ./source/modules/validphys/validphys.tests.rst.
Creating file ./source/modules/validphys/validphys.tests.baseline.rst.
Creating file ./source/modules/validphys/validphys.tests.photon.rst.
Creating file ./source/modules/validphys/validphys.tests.regressions.rst.
Creating file ./source/modules/validphys/validphys.theorycovariance.rst.
Creating file ./source/modules/validphys/modules.rst.
Creating file ./source/modules/n3fit-code/n3fit.rst.
Creating file ./source/modules/n3fit-code/n3fit.backends.rst.
Creating file ./source/modules/n3fit-code/n3fit.backends.keras_backend.rst.
Creating file ./source/modules/n3fit-code/n3fit.hyper_optimization.rst.
Creating file ./source/modules/n3fit-code/n3fit.io.rst.
Creating file ./source/modules/n3fit-code/n3fit.layers.rst.
Creating file ./source/modules/n3fit-code/n3fit.scripts.rst.
Creating file ./source/modules/n3fit-code/n3fit.tests.rst.
Creating file ./source/modules/n3fit-code/n3fit.tests.regressions.rst.
Creating file ./source/modules/n3fit-code/modules.rst.
Running Sphinx v5.0.2
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid langauge code. Falling back to 'en' (English).

Extension error:
Could not import extension sphinxcontrib.bibtex (exception: No module named 'sphinxcontrib.bibtex')
make: *** [html] Error 2
```

**Comment by mariaubiali** [comment]
@Radonirinaunimi by deactivating and activating I find the correct variables

```
(nnpdf_env) MacBook-Pro:sphinx mariaubiali$ echo $CONDA_PREFIX
/Users/mariaubiali/hep/miniconda3/envs/nnpdf_env
(nnpdf_env) MacBook-Pro:sphinx mariaubiali$ python --version
Python 3.11.0
```

**Comment by scarlehoff** [comment]
Ah, the new issue is only packages missing.

To get all packages in one go you can probably do `conda install nnpdf --only-deps` to get the full set of dependencies.


Btw, sort of an aside, but the other possibility is to install with pip instead of with conda:

```
pip install .[docs]
```

(it is necessary to use `[docs]` to install the dependencies require to build the docs)

**Comment by mariaubiali** [comment]
that works! I did 
```
pip install sphinxcontrib-bibtex
pip install sphinx-rtd-theme
```
and now it works. Will start updating the documentation now. Thanks for your help!

**Comment by RoyStegeman** [comment]
Good, I assume this issue can be closed.
