### ISSUE TITLE
Changes needed to enable Python 3.12

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/nnpdf#1970]
We have a number of dependencies that would be blocking us from using Python 3.12:

- [x]  The `MultiDense` layer is not compatible with Tensorflow 2.16 (#1968) (fixed in #1975)
- [x] Recommonmark is no longer updated and it breaks for 3.12 due to newer versions of sphinx (https://github.com/NNPDF/nnpdf/issues/1967#issuecomment-1972957899) (in #1708 sphinx is pinned to 5)
- [x] Curio is no longer updated but the version of [reportengine](https://github.com/NNPDF/reportengine) we use depends on it.. Might be fixed by moving to dask but there are some small changes in reportengine needed for that https://github.com/NNPDF/reportengine/pull/61

Please add any other issues as you find them.

**Comment by RoyStegeman** [comment]
@achiefa can you take care of  `recommonmark`? It's a matter of updating the documentation so that it's no longer required at all. If you'd like we can discuss together what needs to be done exactly.

**Comment by achiefa** [comment]
@RoyStegeman yes, I'd like to discuss it together. But in principle I would say yes.

**Comment by scarlehoff** [comment]
I've pinned sphinx in #1708, it seems that version 5 still works with recommonmark (even in 3.12) so that it can be used.

We still should remove all markdown files because this is only a temporary patch and will eventually break as well.
