### ISSUE TITLE
Datasets name changes

### ISSUE THREAD

**Issue by Cmurilochem** [NNPDF/nnpdf#1984]
Hi @scarlehoff. 
When testing the calculation of [phi](https://github.com/NNPDF/nnpdf/blob/6d785bed6be894d84061a4015e37a71f6bb24f36/n3fit/src/n3fit/tests/test_hyperopt.py#L71) in the [hyperopt_loss](https://github.com/NNPDF/nnpdf/tree/hyperopt_loss) branch, I have the following:
```python
def get_experimental_data(dataset_name="NMC", theoryid=399):
    """Get experimental data set using validphys.

    Returns a list defined by the data set as
    `validphys.core.DataGroupSpec`.
    """
    loader = Loader()
    ds = loader.check_dataset(dataset_name, theoryid=theoryid, cuts="internal")
    return loader.check_experiment("My DataGroupSpec", [ds])
```
After rebasing this morning, I have an error:
```
E               validphys.loader.LoaderError: Trying to use a new theory with an old commondata format, surely it must be a mistake: NMC

/usr/share/miniconda/envs/test/lib/python3.12/site-packages/validphys/loader.py:728: LoaderError
----------------------------- Captured stderr call -----------------------------
Warning: : Error trying to read NMC, falling back to the old format reader
Error: : Trying to read NMC in the old format. Note that this is deprecated and will be removed in future releases
```

Do you have any clue on how to solve this?
Thank you!

**Comment by Cmurilochem** [comment]
Thanks @Radonirinaunimi. With the new name, my test still fails with a new error: `validobj.errors.ValidationError: Missing `data_uncertainties` for NMC_NC_NOTFIXED_P_EM`

**Comment by scarlehoff** [comment]
The new names are now in the runcard in #1986
