### ISSUE TITLE
Problem with installing nnpdf

### ISSUE THREAD

**Issue by lucarottoli** [NNPDF/nnpdf#2010]
Hi, I am trying to install nnpdf on my new Mac Pro Arm. Currently the installation fails with the following conflict:

`Could not solve for environment specs
The following packages are incompatible
├─ nnpdf is installable with the potential options
│  ├─ nnpdf [4.0.9.100+g402e58c2e|4.0.9.112+g40ed828b2|...|4.0.9.98+g79e8adfd7] would require
│  │  └─ python >=3.9,<3.12  with the potential options
│  │     ├─ python [3.10.0|3.10.1|...|3.9.9], which can be installed;
│  │     └─ python 3.12.0rc3 would require
│  │        └─ _python_rc, which does not exist (perhaps a missing channel);
│  ├─ nnpdf [4.0.9.113+g4bd40325a|4.0.9.116+g9823e58f3|...|4.0.9.99+ge0cb4c254] would require
│  │  └─ blas ==1.0 *mkl*, which does not exist (perhaps a missing channel);
│  ├─ nnpdf [4.0.9.134+gb3fc6c637|4.0.9.136+g06db65ca3] would require
│  │  └─ scikit-learn >=1.4.1 , which conflicts with any installable versions previously reported;
│  └─ nnpdf [4.0.9.213+g30523e21d|4.0.9.213+g51933eed0|...|4.0.9.269+g06f7d46c4] would require
│     └─ mongodb but there are no viable options
│        ├─ mongodb [6.0.0|6.0.1|6.0.2] would require
│        │  └─ icu >=70.1,<71.0a0 , which conflicts with any installable versions previously reported;
│        └─ mongodb 6.0.12 would require
│           └─ icu >=73.2,<74.0a0 , which conflicts with any installable versions previously reported;
└─ pin-1 is not installable because it requires
   └─ python 3.12.* , which conflicts with any installable versions previously reported.

Pins seem to be involved in the conflict. Currently pinned specs:
 - python 3.12.* (labeled as 'pin-1')`

I do not think that the issue is related to ARM, but I can provide further details if needed.

**Comment by lucarottoli** [comment]
Thanks, your suggestion worked. To be honest I don't get what was the problem. I tried already a new installation (I even re-installed miniconda). The command below failed:

```
conda create -n nnpdf_clean nnpdf
Channels:
 - https://packages.nnpdf.science/private
 - https://packages.nnpdf.science/public
 - defaults
 - conda-forge
Platform: osx-arm64
Collecting package metadata (repodata.json): done

Solving environment: / warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
[...]
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides blas ==1.0 *mkl* needed by nnpdf-4.0.9.113+g4bd40325a-py_0

Could not solve for environment specs
The following packages are incompatible
└─ nnpdf is not installable because there are no viable options
   ├─ nnpdf [4.0.9.100+g402e58c2e|4.0.9.112+g40ed828b2|...|4.0.9.98+g79e8adfd7] would require
   │  └─ lhapdf but there are no viable options
   │     ├─ lhapdf 6.5.0 would require
   │     │  └─ libcxx >=15.0.7 , which conflicts with any installable versions previously reported;
   │     └─ lhapdf 6.5.4 would require
   │        └─ libcxx >=16.0.6 , which conflicts with any installable versions previously reported;
   ├─ nnpdf [4.0.9.113+g4bd40325a|4.0.9.116+g9823e58f3|...|4.0.9.99+ge0cb4c254] would require
   │  └─ blas ==1.0 *mkl*, which does not exist (perhaps a missing channel);
   ├─ nnpdf [4.0.9.134+gb3fc6c637|4.0.9.136+g06db65ca3] would require
   │  └─ scikit-learn >=1.4.1 , which conflicts with any installable versions previously reported;
   └─ nnpdf [4.0.9.175+g2ec03d5a1|4.0.9.177+g8679dca4e|...|4.0.9.269+g06f7d46c4] would require
      └─ mongodb but there are no viable options
         ├─ mongodb [6.0.0|6.0.1|6.0.2] would require
         │  └─ boost-cpp >=1.74.0,<1.74.1.0a0 , which conflicts with any installable versions previously reported;
         └─ mongodb 6.0.12 would require
            └─ icu >=73.2,<74.0a0 , which conflicts with any installable versions previously reported.

```

whereas `conda create -n nnpdf_clean nnpdf -c conda-forge -c https://packages.nnpdf.science/public` worked. I did't see any change in my channels, though... thanks a lot!

**Comment by scarlehoff** [comment]
I'm not sure either, my guess would be that from defaults the latest version of nnpdf that works is 4.0.9.100, and that was before we made it 100% compatible with arm (which only happened one or two weeks ago). Instead with conda-forge it works fine.

(before you could install it manually from the repository and it would work, but you had to play a bit with the dependencies).

**Comment by RoyStegeman** [comment]
Good to see that this has already been resolved, but just a small obervation: in the channel ordering `defaults` comes before `conda-forge`
```
Channels:
 - https://packages.nnpdf.science/private
 - https://packages.nnpdf.science/public
 - defaults
 - conda-forge
```

If miniconda solves with a `strict` channel priority (which I believe for recent versions should be the default) it will search for any given package in the order the channels are in. This means that if it finds any version of e.g. `matplotlib` in `defaults`, it will not keep searching for it in in `conda-forge`, even if the version in `defaults` causes the environment to be impossible to solve. 

The solution to this may be to swap the order of `defaults` and `conda-forge` in your `.condarc` file, or to add `channel_priority: flexible` to it (this will increase the time it takes to solve an environment).

**Comment by lucarottoli** [comment]
Hi @RoyStegeman , sorry I missed your message. That makes sense. I will swap the defaults then. Thanks!
