### ISSUE TITLE
Load positivity datasets with cuts

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/nnpdf#2058]
We always skip the cuts when loading positivity datasets. I'm not entirely sure why (it has always been done like that, maybe some parts of the code needs the positivity not to be cut)

https://github.com/NNPDF/nnpdf/blob/f1a0eb09f1d451663234ee5d47972334aa5ef5ee/validphys2/src/validphys/core.py#L590

However, now the positivity sets and fktables should be in the same footing as the others, so in principle we could also cut (in `x` for instance). Maybe removing this method (so that it goes to the parent, which applies the cut) is enough, but it should be tested.

**Comment by RoyStegeman** [comment]
> However, now the positivity sets and fktables should be in the same footing as the others

Why? Positivity is quite special. I don't think we should e.g. not include positivity if we change the Q2 cut to above 5Gev2 if we want to test the stability for example

**Comment by RoyStegeman** [comment]
Okay, as long as it's not by default I don't see any problem

**Comment by comane** [comment]
Hi @scarlehoff, just to make sure I understand this correctly.
Would you like to have some rules in `cuts/filter.yml` that impose cuts in x for the positivity datasets?

Another options would be that of creating a new kinematics file eg for `XGL` -> `NNPDF_POS_2P24GEV_XGL_highX` where we simply remove the kinematic points that are below a certain treshold

**Comment by comane** [comment]
Ok, I see.

Then I think that it's probably not enough to just remove the `load_commondata` from `LagrangeSetSpec`, it seems that positivity datasets are assigned a `Cuts` class whereas DataSetSpecs are assigned an `InternalCutsWrapper` which is the one aware of the rules.
