### ISSUE TITLE
CIs fail because of a new version of scipy

### ISSUE THREAD

**Issue by Radonirinaunimi** [NNPDF/nnpdf#2117]
From [v1.14.0](https://docs.scipy.org/doc/scipy-1.14.0/reference/generated/scipy.integrate.simpson.html), the `simps` method from `scipy.integrate` has been removed, causing all the CIs to fail. The packages that depend on `scipy` are `eko` and `hyperopt`, and both of them do not impose a cap on which version should be installed.

Also the `arc_lengths` function in vp uses `simps`.

**Comment by felixhekhorn** [comment]
As eko does not use this function, I don't think eko needs to react, right? #2119 should be a valid fix (PS: the relevant link is [this](https://docs.scipy.org/doc/scipy-1.14.0/release/1.14.0-notes.html#expired-deprecations) :upside_down_face:)

**Comment by RoyStegeman** [comment]
> eko does not use this function

And neither does hyperopt, so indeed #2119 closes this
