### ISSUE TITLE
Take the $USER variable as author if not given

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/nnpdf#2130]
In order to avoid having reports uploaded with the wrong name or "Lazy Person".

**Comment by RoyStegeman** [comment]
I understand your proposal. `author` is already a required key for the metadata file.

**Comment by scarlehoff** [comment]
Rather, I would write in the examples $USER or something like that.

**Comment by RoyStegeman** [comment]
I don't know if that's a good idea. At least now people are forced to put something in that field, and it's not as if there are a lot of reports accidentally being uploaded by "Lazy Person"

**Comment by scarlehoff** [comment]
Ok, fine. I still would not use names of other people though (there are a few uploaded with the wrong names)

**Comment by RoyStegeman** [comment]
> Better to have a damning "lazy" or "guilty"

This I agree with
