### ISSUE TITLE
Example where pineappl grids are used?

### ISSUE THREAD

**Issue by LucianHL** [NNPDF/nnpdf#2161]
Hi, following from issue #2155 I have got the applgrid to pineappl working and pineko running with the examples provided. Is there actually an example where .pineappl format FK grid files are used for a particular dataset in the nnpdf code? At the moment all I am seeing is .dat files in (e.g.) .../theory_211/fastkernel/ whereas `pineko` produces .pineappl files.

This is just to give me a clearer picture of what is needed for the nnpdf code to read in a new FK table in that format. Apologies in advance if I am misunderstanding something here (quite possible).

**Comment by scarlehoff** [comment]
Hi @LucianHL `theory_211` is using the old fktables, for the new ones (with `pineappl` files) you need to use `40001000` 

For how to use it for a particular dataset, check for instance this one:
https://github.com/NNPDF/nnpdf/blob/f5072bdcbd46c3e773cfe2f1cf63c89f6f2d27ab/nnpdf_data/nnpdf_data/commondata/CMS_WPWM_13TEV_ETA/metadata.yaml#L95

The dataset name in this case is `CMS_WPWM_13TEV_ETA_WM` and the FKTable that will be loaded is `CMS_WPWM_13TEV_ETA_WM.pineapl.lz4`

> Apologies in advance if I am misunderstanding something here (quite possible).

We should be the ones apologising! We are now in between pipelines (and importantly, people...) so the documentation is a bit outdated in several places. We are for instance changing the name convention of theories and datasets.

For what is worth, you can still use the old names of the datasets, here's a translation: https://github.com/NNPDF/nnpdf/blob/master/nnpdf_data/nnpdf_data/commondata/dataset_names.yml if there's a dataset in particular you'd like to modify.

Theory 40001000 should include all datasets that were used in NNPDF4.0 (Here's a runcard with all names https://github.com/NNPDF/nnpdf/blob/master/n3fit/runcards/examples/nnpdf40-like.yml but with theory 40000000, intrinsic charm).

**Comment by LucianHL** [comment]
Thanks @scarlehoff I will give that a go
