### ISSUE TITLE
Datasets should know their default configuration

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#226]
When one specifies a dataset without options in the runcard (i.e. cfactors, training fractions, systematics) it should do the right thing as opposed to the bare thing.

To that end we should have in the metadata what the default configuration is (which in turn may depend on the theory settings and whatnot, much like the cuts).

A subtlety is that we are making the runcard less reproducible (i.e. what if the default cfactors change) so there should be a mechanism for a fit to know that (perhaps by copying the metadata, and adding a mechanism to read the metadata from the result). An added subtlety on the subtlety is that there is a distinction between bugfixes (ups, we forgot the normalization cfactor) and genuine additions (we now have the elwctroweak corrections), and it is for discussion whether those should be treated the same or not. The simplest would be yes, and there are two modes, current defaults and fit defaults.

Now we only have the fit defaults, which are problematic because one has to copy the settings in all the runcards (I doubt anybody has ever written manually a runcard after the first one) and it is all to easy (and too difficult to notice) to screw up a cfactor or similar. 

As an added bonus the validphys runcards (which are mostly handwritten) would get nicely simplified for most common cases.

Somewhat related to #224 and #35.

**Comment by scarlehoff** [comment]
Now default is the non-variant version. Anything else is a variant.
