### ISSUE TITLE
Binary FKTables

### ISSUE THREAD

**Issue by scarrazza** [NNPDF/nnpdf#23]
<a href="https://github.com/Zaharid"><img src="https://avatars2.githubusercontent.com/u/5675858?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Zaharid](https://github.com/Zaharid)**
_Friday Jun 23, 2017 at 16:20 GMT_
_Originally opened as https://github.com/NNPDF/libnnpdf/issues/11_

----

The alphas fits are becoming unbearable due to the slowness of the fktable processing.  As a first step can we simply compress each fktable individually? That's already quite a speed up, independent of everything else (and should be working now, right?).

For the binary, I think looking at something like avro is better than inventing the format ourselves:

https://avro.apache.org/docs/current/spec.html

in my opinion it has the things we need (and not many we don't).

**Comment by felixhekhorn** [comment]
I guess PineAPPL grids are binary, so we can close - do you agree? @cschwan @scarrazza @Zaharid

**Comment by cschwan** [comment]
Yes, they are binary; more concretely the PineAPPL files are
- the [Grid](https://docs.rs/pineappl/latest/pineappl/grid/struct.Grid.html) data structure from the [PineAPPL crate](https://crates.io/crates/pineappl),
- [serialized](https://serde.rs/)
- with [bincode](https://github.com/bincode-org/bincode) and
- prefixed with a small header[^1], 
- transparently[^2] compressed using [LZ4](https://lz4.github.io/lz4/), one of the fastest decompression algorithms.

As for the size, have a at look <https://github.com/N3PDF/pineappl/issues/45#issuecomment-1239954186> in which I discuss the conversion of the complete <https://github.com/NNPDF/applgrids> repository. For (PineAPPL-)FK tables I would expect a similar picture.

[^1]: the file header allows us to completely change all data structures and serialization formats in newer version if we decide we need that
[^2]: transparently means that you can run `lz4 -d grid.pineappl.lz4` to decompress the file, which will get you the header + serde/bincode output. The decompressed output can also be read by every API as well as the compressed file

**Comment by RosalynLP** [comment]
:)
