### ISSUE TITLE
Additional sources of theory uncertainty

### ISSUE THREAD

**Issue by nhartland** [NNPDF/nnpdf#285]
We have a plan for how new theory covariance matrices should be generated and communicated in Issue #186. However in that issue the solution to point (3) remains unspecified. This issue is to discuss how it is to be solved. To recap:

> **Point 3 : How do we specify which theory errors we want to add to which matrices.**
> We want to deprecate the existing system for fudge-factors and C-factor errors (sys10)
> and have them included in the theory matrices by vp-setupfit. How the construction of the matrices is specified is undecided.
> 
> It should:
> Express which theory errors (MHOU, C-factor, fudge) should be applied to which matrices (fitting, sampling). This should be driven by the fit runcard. 

At the code p.c today it was decided that we need to be able to handle, very generally, both correlated and uncorrelated uncertainties (possible also multiplicative/additive) from external sources (i.e a plain text file). This requires a new scheme for the specification of these uncertainties.

One possibility is a `CommonData` type file format with `CORR` `UNCORR` and named systematics for a completely general treatment (`CommonTheory`?). 

The strategy would be that `validphys` reads these files and builds a theory covariance matrix from them. This can then be used to augment the theory matrix from scale variations.

The structure of such a file should be discussed here, along with the control/configuration apparatus required in order to manage all the different possible combinations of theory errors.

**Comment by scarlehoff** [comment]
This ship has sailed (and probably sinked just out of the harbour)
