### ISSUE TITLE
Add facility to quickly see the nnprofile path

### ISSUE THREAD

**Issue by scarrazza** [NNPDF/nnpdf#31]
<a href="https://github.com/Zaharid"><img src="https://avatars2.githubusercontent.com/u/5675858?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Zaharid](https://github.com/Zaharid)**
_Wednesday Jul 26, 2017 at 07:32 GMT_
_Originally opened as https://github.com/NNPDF/libnnpdf/issues/38_

----

It should be simple to query where the nnprofile is, for example in nnpdf-config. However it should be able to mind the environment variable.

**Comment by scarlehoff** [comment]
Now it is _always_ in `~/.config/NNPDF/nnprofile.yaml`as XDG intended.
