### ISSUE TITLE
FKs, FKsets and data

### ISSUE THREAD

**Issue by scarrazza** [NNPDF/nnpdf#380]
We need a:
- a list of FK tables:
  - with sigma, xgrid, nx, nd, basis
- a list of data/expdata
  - with cv, covmat
- a `noFKset` object containing a list with  `[map([FKs], op, exp), ...]` containing all the required inputs for the convolution.

**Comment by scarlehoff** [comment]
Not exactly in the same spirit but in any case closed by #1680
