### ISSUE TITLE
Generation of NNLO FKTables with scale variations for collider experiments

### ISSUE THREAD

**Issue by lucarottoli** [NNPDF/nnpdf#409]
To run the last fit in https://github.com/NNPDF/nnpdf/issues/394 (or for future fits with scale variations) it would be necessary to produce NNLO FKTables with APFEL. This requires

- [x] implement alternative scale variation method with APFEL
- [ ] merge the scale variation method into APFEL master
- [ ] create new theories (this might require a small modification of apfelcomb)
- [ ] compare new theories for DIS with old theories for DIS to compare the differences
- [ ] rescale the C-factors to allow for scale variations with apfel

**Comment by scarlehoff** [comment]
(this is now done but through eko instead of apfel)
