### ISSUE TITLE
Validphys as a service

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#435]
@wilsonmr is rightly asking how are we supposed to compute theory covariance matrices in practice; these require up to nine theories. There is the problem that these don't fit on my laptop (and the parquet format is unlikely to do them smaller, rather the opposite). Likewise they are likely to run against disk space quotas everywhere. It will be very impractical to do anything concerning theory uncertainties. There is also the problem that the theory covmats take quite a while to compute (although less than the experimental covmats with the stupid algotithm we are using). Furthermore we currently don't have particularly good ways of making sure that the covmat you are using actually corresponds to what you want, unless you compute is as a part of the same validphys run (see #224  for a discussion).

I am wondering if we could not have a central central server that does at least that part of the calculation (although it is obviously possible to make it run a whole validphys report). In that way users would not have to download a massive amount of resources and critical parts could be cached and reused. The interface could look like `vp-submit <runcard>` and you get an URL back with the result. Combined with #224 that could take care of the covmats. 

Of course this all critically depends on the server situation, which is going to get better *soon* since September or so.

**Comment by scarlehoff** [comment]
This would be very nice, but sadly this is way out of what we can afford in terms of human resources :(
