### ISSUE TITLE
Incorporating general theory covmats into nnpdf code

### ISSUE THREAD

**Issue by RosalynLP** [NNPDF/nnpdf#628]
In the future we want to be able to incorporate general theory covmats into fits, i.e. contributions from nuclear uncertainties, higher twist uncertaintes etc.

Scale variation theory covmats are computed at the `vp-setupfit` level via a production rule `produce_nnfit_theory_covmat` in` config.py`. We want to be able to add arbitrary covmats from file, in other words ones which are not computed inside `validphys` each time.

It would be simplest to add per-dataset contributions (i.e. block diagonal by dataset) by loading in a covmat for each dataset. However, the correct cuts would need to be applied - presumably this can be done similarly to how experiment covmats are loaded in.

However, for more general theory covmats which include correlations between experiments things will be more difficult with the current set-up in` validphys`. Ideally we would want to load in the total arbitrary theory covmat and add it to the scale variation covmat at the` produce_nnfit_theory_covmat `stage. But this is after cuts have been applied so we would need a way to make the correct cuts on the whole theory covmat at this late stage, and I cannot yet see a clear way to do this.

**Comment by scarlehoff** [comment]
This is now done!
