### ISSUE TITLE
Positivity sets should be just datasets without experimental data

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#759]
There is no in principle reason why we shouldn't have cuts and compound opertators in the positivity specs. We already found it convenient to extend them in the past, e.g. by adding plotting files for them.

On the contrary maintaining a separate structure leads to some code duplication (see e.g. #757), which is not that bad in itself, but still it is one more needless special case to consider.

As far as I can tell, this would be a fairly minor code change in vp once we get rid of libnnpdf and would not require modifying any new files.

cc @enocera @wilsonmr

**Comment by scarlehoff** [comment]
Closed with #1678
