### ISSUE TITLE
Improve handling of random seeds

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#77]
Validphys should try very hard to make results reproducible. This in turn requires that random generators are seeded in a well defined way. Each provider that uses random numbers should have its own random state and not depend on some global state (and e.g. the order of the actions which is undefined in reportengine). However:

 - The seeds must be different for different providers to avoid spurious correlations.
 - Users cannot be required to write a random seed for every function. 

A possible solution is to mix the string with something that depends on the provider such as its name, as in:

```
provider_seed = int.from_bytes(provider.__name__.encode(), byteorder='little')
seed += provider_seed
```

(where `provider` is to be retrieved with some metaprogramming magic).

Ideally it should be possible to:

 - Not supply seeds as inputs in the runcard.
 - Have the automatically generated seed written somewhere.
 - Be able to reproduce the result with the generated seed.

**Comment by scarlehoff** [comment]
This is now done. We are _quite_ reproducible unless tensorflow / numpy are updated.
