### ISSUE TITLE
Build packages from branches

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#780]
We should try to have packages from non-master branches that can be trivially used to e.g. run fits.

At the moment we can upload the packages that get built, but those are indistinguishable from nnpdf-master so that is not very good. Instead we should have:

  - Different package names.
  - Packages that are mutually incompatible (you can only have one NNPDF package from any branch installed).

Conda used to make that very complicated but now there is a feature that may be just right:
https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/packages.html#mutex-metapackages

The idea would be that you can just do `conda install nnpdf-flbasis` and run that out of the box.

**Comment by scarlehoff** [comment]
since we can install now directly with pip from the repository, running from a branch in e.g., a cluster is trivial

**Comment by scarlehoff** [comment]
But actually, this is now closed by #2305 :)
