### ISSUE TITLE
Derivative of the neural net

### ISSUE THREAD

**Issue by tgiani** [NNPDF/nnpdf#787]
It would be useful to access the derivative of the neural nets within n3fit, printing it (or some function of it) on a LHAPDF grid at then end of a fit. This would allow for example to compute the effective exponents of 1604.00024, without implementing numerical derivatives.

**Comment by scarlehoff** [comment]
Did you ever try this out @tgiani ?

**Comment by tgiani** [comment]
mm not as far as I remember, I m not sure what was the point of this
