### ISSUE TITLE
N3FIT dictionaries are confusing

### ISSUE THREAD

**Issue by siranipour** [NNPDF/nnpdf#800]
N3FIT makes extensive use of dictionaries but they very quickly get rather unwieldy, one such example is:

https://github.com/NNPDF/nnpdf/blob/a70e6f746e1d60041920f9827aa9cac6ca7a5fcf/n3fit/src/n3fit/io/reader.py#L175

which returns a list of dictionaries which map to lists containing more dictionaries which map to more lists... and it just becomes an absolute mess trying to keep track of what it is I am trying to dig to.

There must be an easier way of structuring these things. In general n3fit appeals to dictionaries quite a bit which makes me wonder if there is any other way of doing this.

**Comment by scarlehoff** [comment]
This is now tracked by #1683

**Comment by Zaharid** [comment]
cc @comane

**Comment by scarlehoff** [comment]
disclaimer: This was a conversation from 3 years ago so not sure if whatever I wrote is applicable or makes any longer sense.

**Comment by Zaharid** [comment]
Last time I looked, there still were a lot of dictionaries :)

**Comment by scarlehoff** [comment]
Not that, I'm talking about what I wrote which probably contains a negative amount of information :__
