### ISSUE TITLE
Open sourcing the code

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#954]
We have agreed to make the NNPDF code public, more or less along the release of 4.0.

This is to discuss what actions should be taken for that to happen.

  - We would like to have reasonable documentation of the code. That is discussed in #656.
  - It has been argued that we want to "get rid" of C++ to some extend. That is discussed in #952.
  - We may want to add some private component to the code. That's #953.
  - We should probably add a LICENCE. Possibly GPL?
  - (Potentially we could try again github actions.)

Is there anything else?

**Comment by scarrazza** [comment]
I think we can close this issue.
